InfiniTimeOrg/InfiniTime

- src/drivers/TwiMaster.cpp
Hi JF002,
When I tried to compile the new code, I was not able since you include "sdk/" in your path, and mine is in another folder.
So I corrected headers inclusion
BR,
Memiks.
> Correct including path

- README.md
I don't know what you mean with line 86, because it's the same as, or different than. I just assumed the same as
Basically i did nothing that would actually help the project, but since i don't own the skills or a pinewatch to contribute code (i can't even write a wayland compositor yet, and my only watch related projects are 2 garmin watchfaces with 8k combined downloads) ai did this, to at least help you guys with something.
And i do not expect/want to appear on this list of peolle, as i did nothing useful.
> Fixed typo, fixed caps and clarified one line more + iOS caps fix (not IoS)

- .gitignore
Added a few more folders to .gitignore before they end up in the repository.
> Added a few more folders to gitignore before they end up in the repository

- .idea/codeStyles/Project.xml
This PR adds a code style configuration for the CLion IDE and thus should remove the need for people to always do the configuration themselves.
> Added a code style configuration to the repository

- src/displayapp/screens/Screen.h
- src/displayapp/screens/Tab.cpp
- src/systemtask/SystemTask.cpp
- src/systemtask/SystemTask.h
This just fixes a small typo in SystemTask and a few other very minor changes.
> Fixed a typo in SystemTask

- src/displayapp/screens/Brightness.cpp
- src/displayapp/screens/Clock.cpp
- src/displayapp/screens/DropDownDemo.cpp
- src/displayapp/screens/FirmwareUpdate.cpp
- src/displayapp/screens/FirmwareValidation.cpp
- src/displayapp/screens/Gauge.cpp
- src/displayapp/screens/Label.cpp
- src/displayapp/screens/Meter.cpp
- src/displayapp/screens/Modal.cpp
- src/displayapp/screens/Tile.cpp
- src/systemtask/SystemMonitor.h
This small PR changes the usage of NULL to nullptr. (Squash merge for nicer commit log)
> Switched from NULL to nullptr

- .idea/codeStyles/Project.xml
- src/CMakeLists.txt
- src/displayapp/screens/InfiniPaint.cpp
- src/displayapp/screens/InfiniPaint.h
- src/displayapp/screens/Screen.h
- src/logging/NrfLogger.cpp
- src/systemtask/SystemTask.cpp
This PR contains very minor formatting, diagnostic and documentation changes
> Minor formatting, diagnostic and documentation changes

- doc/buildAndProgram.md
The difference in the example caused some confusion for at least one person.
> Update arm-gcc toolchain in example

- src/CMakeLists.txt
- src/components/ble/AlertNotificationClient.cpp
- src/components/ble/AlertNotificationClient.h
- src/components/ble/BleClient.h
- src/components/ble/CurrentTimeClient.cpp
- src/components/ble/CurrentTimeClient.h
- src/components/ble/NimbleController.cpp
- src/components/ble/NimbleController.h
- src/components/ble/ServiceDiscovery.cpp
- src/components/ble/ServiceDiscovery.h
Multiple issues were raised about BLE connection and reconnection: https://github.com/JF002/Pinetime/issues/78, https://github.com/JF002/Pinetime/issues/76, https://github.com/JF002/Pinetime/issues/70.
This PR should improve the reliability of the connection and reconnection.
> Improve ble connection

- bootloader/README.md
- src/components/gfx/Gfx.cpp
- src/components/gfx/Gfx.h
- src/displayapp/LittleVgl.cpp
I assume this was intended to be "Transfer"
> Fixed typo (Transfert -> Transfer)

- src/displayapp/screens/SystemInfo.cpp
> Fixed battery percentage readout in the menu display

- src/displayapp/screens/SystemInfo.cpp
- src/displayapp/screens/SystemInfo.h
> Add source code license and link to github to system app

- src/CMakeLists.txt
- src/displayapp/Apps.h
- src/displayapp/DisplayApp.cpp
- src/displayapp/screens/ApplicationList.cpp
- src/displayapp/screens/Twos.cpp
- src/displayapp/screens/Twos.h
I played a lot of 2048 on my Pebble Time and figured it might be a nice addition to Infinitime. Implemented with an LVGL table and played by swiping the screen.
> Adds 2048 clone game

- .gitpod.yml
- docker/.gitpod.Dockerfile
Little configuration to give https://gitpod.io users an environment with the SDKs pre-installed
Gitpod is an amazing tool, even without this PR being accepted, it's worth your time to have a peek!
> Custom Dockerfile for gitpod.io

- doc/ble.md
- src/components/ble/MusicService.cpp
- src/components/ble/MusicService.h
Add custom BLE service UUID guidelines in the documentation.
Adapt the music service to these guidelines.
> Fix music service UUID

- src/CMakeLists.txt
This PR just makes the CMakeLists a tiny bit more consistent
> Updated CMakeLists.txt to be more consistent

- src/displayapp/screens/SystemInfo.cpp
> Update project URL in SystemInfo

- src/components/gfx/Gfx.cpp
- src/displayapp/LittleVgl.cpp
- src/drivers/St7789.cpp
- src/drivers/St7789.h
After some investigation I managed to solve the problem that caused the image on the screen to be left with some "garbage".
I also took the opportunity to optimize the function  **LittleVgl::FlushDisplay** a little.
Before :
After :
> FIX screen corruption (Issue #213)

- src/displayapp/DisplayAppRecovery.cpp
- src/recoveryLoader.cpp
Fixing build errors in DisplayAppRecover.cpp and recoveryLoader.cpp after new updates to display driver
> fix display driver issues in recovery

- README.md
Shameless plug to my article in your repo as you suggested in the chat :)
> Added a link to the stopwatch article.

- src/displayapp/screens/Music.cpp
Adding the same style and color to the buttons in the music app as in the other menus
> Apply theme to Music buttons

- src/displayapp/screens/StopWatch.cpp
- src/displayapp/screens/StopWatch.h
Fixes #284 :)
(fixed on the left, RC1 on the right)
> Fix stopwatch formatting

- src/displayapp/fonts/README.md
Signed-off-by: Kozova1 <mug66kk@gmail.com>
> Fix typo in src/displayapp/fonts/README.md

- src/components/heartrate/Ppg.cpp
- src/components/heartrate/Ppg.h
> Use int8_t for PPG data array

- src/displayapp/DisplayApp.cpp
- src/displayapp/DisplayAppRecovery.cpp
- src/logging/NrfLogger.cpp
This PR adds braces to a few if statements, reduces the amount of warnings and inconsistencies.
> Added braces to a few if statements

- src/displayapp/DisplayApp.cpp
- src/displayapp/DisplayAppRecovery.cpp
- src/logging/NrfLogger.cpp
This PR switches from integers to booleans for infinite loops, gets rid of a few warnings.
> Switched to booleans for infinite while loops

- doc/contribute.md
Fixed typos in the doc/contribute.md using google doc's spelling check system
Changers:
Removed unnecessary spaces on some line endings
Pinetime        -> The Pinetime - Line 11
You                -> Your              - Line 24
You                -> Your              - Line 26
feedbacks      -> feedback       - Line 32
adjustements -> adjustments  - Line 40
an                  -> and                - Line 42
lifes               -> lives               - Line 45
Identation      -> Indentation    - Line 66
This is my first contribution on a public repo :)
> Fixed typos in the doc/contribute.md using google docs’s spelling check system

- src/displayapp/screens/Notifications.cpp
thanks to @Avamander and @MysteriousLog6 for noticing this. I'm honestly surprised that code even compiled.
> fixing my boneheaded mistake

- README.md
- doc/companionapps/Gadgetbridge.md
Hopefully this is useful and will save folks some frustration
> Add note about getting GadgetBridge from F-Droid

- src/displayapp/screens/StopWatch.cpp
Improve alignment
Larger buttons
Buttons on bottom
Keep buttons always visible, but disabled
> Improve stopwatch

- src/displayapp/screens/Steps.cpp
- src/displayapp/screens/SystemInfo.cpp
- src/displayapp/screens/Timer.cpp
- src/displayapp/screens/settings/SettingSteps.cpp
I fixed a missing attribute in LVGL and this allowed me to detect and improve a bunch of format specifiers. 
Hopefully LVGL itself will contain the patch soon as well, but that's yet to be seen.
> Improved a bunch of format specifiers

- src/components/battery/BatteryController.cpp
- src/displayapp/screens/SystemInfo.cpp
This PR just updates the cast style in a few places for more consistency.
> Changed a few C-style casts to static_cast

- README.md
Added metronome to app list as it was missing.
> Add "metronome" to 'apps' in readme

- doc/PinetimeStubWithNrf52DK.md
- doc/ble.md
- doc/branches.md
- doc/buildAndProgram.md
- doc/buildWithDocker.md
- doc/contribute.md
- doc/filesInReleaseNotes.md
Correction in the spelling of documentation.
> Correct spelling issue in documentation

- src/displayapp/screens/SystemInfo.cpp
- src/libs/lv_conf.h
Latest develop builds clean with no warnings with these changes.
> Fix compile warnings

- README.md
added as experimental companion app
> Infini-iOS

- src/components/settings/Settings.h
This seems like it should have caused a bug, but I haven't noticed any.
> Correct change test for wake up mode setting

- doc/contribute.md
Closes https://github.com/InfiniTimeOrg/InfiniTime/pull/233
> Removed an unnecessary space and some punctuation

- doc/MotionService.md
- src/components/ble/MotionService.cpp
Title says it all. I some places the wrong UUID still remained.
> fix Motion Service UUID in doc and code comments

- src/displayapp/screens/WatchFaceAnalog.cpp
- src/displayapp/screens/WatchFaceAnalog.h
Remove unused `ScreenList.h` include.
For `std::abs()` add needed include `<cmath>`.
For the forward declared Settings-Controller add the `Settings.h`
include to the cpp file.
> WatchFaceAnalog: remove unused ScreenList, add needed includes

- src/displayapp/screens/WatchFaceAnalog.cpp
Standardise notification icon to display in top left.
> WatchFaceAnalog : move notification icon

- src/displayapp/screens/settings/SettingSteps.cpp
Removed these accidental usages of NULL instead of nullptr and an unnecessary modifier.
> Switched the usage of NULL to nullptr

- src/components/ble/AlertNotificationService.cpp
- src/displayapp/DisplayApp.cpp
- src/logging/NrfLogger.cpp
> Minor style improvements

- docs/what-is-infinitime/index.md
Add ITD to the list of companion apps
> Add ITD to the list of companion apps

- src/buttonhandler/ButtonHandler.cpp
- src/buttonhandler/ButtonHandler.h
Found one include, that I didn't update
> ButtonHandler: includes relative to src dir

- docs/user-documentation/apps.md
Hi everyone, this is my first contribution :)
I wrote some texts about the apps for the end-user documentation.
I am not using the music and navigation app, so I left those parts blank.
> Watchapp end-user documentation improvements

- .github/workflows/lv_sim.yml
InfiniSim PR https://github.com/InfiniTimeOrg/InfiniSim/pull/10 adds
support for screenshots in png format using a `libpng` submodule. This
new submodule must be added to the lv_sim workflow as well.
> CI: lv_sim: initialize libpng submodule for WITH_PNG=ON screenshot

- docs/build-flash-and-debug/index.md
Building on Windows needs some small tweaks as @[ITCactus](https://github.com/ITCactus) noticed. After those changes building on Windows worked for me.
> Documentation for building on Windows (see #1056)

- src/displayapp/screens/Alarm.cpp
- src/displayapp/screens/FirmwareUpdate.cpp
- src/displayapp/screens/FirmwareUpdate.h
- src/displayapp/screens/FirmwareValidation.cpp
- src/displayapp/screens/FlashLight.cpp
- src/displayapp/screens/HeartRate.cpp
- src/displayapp/screens/Motion.cpp
- src/displayapp/screens/Music.cpp
- src/displayapp/screens/Navigation.cpp
- src/displayapp/screens/Notifications.cpp
- src/displayapp/screens/Paddle.cpp
- src/displayapp/screens/PassKey.cpp
- src/displayapp/screens/Steps.cpp
- src/displayapp/screens/StopWatch.cpp
- src/displayapp/screens/Tile.cpp
- src/displayapp/screens/Timer.cpp
- src/displayapp/screens/Twos.cpp
- src/displayapp/screens/WatchFaceAnalog.cpp
- src/displayapp/screens/WatchFaceDigital.cpp
- src/displayapp/screens/WatchFacePineTimeStyle.cpp
- src/displayapp/screens/settings/QuickSettings.cpp
- src/displayapp/screens/settings/SettingShakeThreshold.cpp
Improvements from #521, without conflicts.
> Replace lv_label_set_text where possible

- src/displayapp/screens/FirmwareUpdate.cpp
Avoid using floats.
Increase bar resolution.
Other small fixes.
> Firmware update screen fixes

- src/components/ble/MusicService.cpp
- src/components/ble/MusicService.h
- src/displayapp/screens/Music.cpp
- src/displayapp/screens/Music.h
Update the progress in the music service, instead of the app.
I'm unsure if this is the best way to fix it, and this probably warrants more thorough testing, but in my limited testing everything seems to work correctly.
Fixes #127
> Update track progress in MusicService

- src/displayapp/screens/FirmwareValidation.cpp
- src/displayapp/screens/HeartRate.cpp
- src/displayapp/screens/List.cpp
- src/displayapp/screens/Tile.cpp
- src/displayapp/screens/settings/QuickSettings.cpp
- src/displayapp/screens/settings/SettingBluetooth.cpp
- src/displayapp/screens/settings/SettingChimes.cpp
- src/displayapp/screens/settings/SettingDisplay.cpp
- src/displayapp/screens/settings/SettingTimeFormat.cpp
- src/displayapp/screens/settings/SettingWakeUp.cpp
- src/displayapp/screens/settings/SettingWatchFace.cpp
Fix some clang-tidy warnings in screens.
> Fix some warnings

- README.md
See [this](https://github.com/InfiniTimeOrg/InfiniLink/commit/58c5caf23d18386e0618948515f7af28dac0b263) commit.
> Update link to InfiniLink and mention that it is unmaintained

- src/displayapp/screens/ApplicationList.cpp
- src/displayapp/screens/ApplicationList.h
- src/displayapp/screens/settings/Settings.cpp
- src/displayapp/screens/settings/Settings.h
Apps and settings are now stored in a single array (two arrays in total). ~~Adding more entries will automatically create more screens.~~
I'm assuming there's a reason for std::function, because I don't know exactly what it does.
> Automatically create screens for applist and settings

- src/displayapp/screens/FlashLight.cpp
- src/displayapp/screens/FlashLight.h
Includes tiny code tweaks.
~~Depends on #1180~~
Fixes #836
> Flashlight default to max brightness

- src/CMakeLists.txt
- src/displayapp/screens/Label.cpp
- src/displayapp/screens/Label.h
- src/displayapp/screens/List.cpp
- src/displayapp/screens/List.h
- src/displayapp/screens/Tile.cpp
- src/displayapp/screens/Tile.h
- src/displayapp/widgets/PageIndicator.cpp
- src/displayapp/widgets/PageIndicator.h
Simply moved the code to a new class.
> Add PageIndicator widget to reduce code duplication

- .github/workflows/docker.yml
- .github/workflows/format.yml
- .github/workflows/lv_sim.yml
- .github/workflows/main.yml
@JF002 This pull request fixes the issue mentioned [here](https://github.com/InfiniTimeOrg/InfiniTime/pull/1227#issuecomment-1179694202).
Also fix issue where the Docker workflow fails on pull requests when the user who made the pull request doesn't have the secrets set.  
Also allow other workflows to be triggered manually.  
Also don't trigger any workflows on pull requests to master, as there shouldn't be any pull requests against master.
> Fix Docker workflow not pushing on manual trigger

- README.md
- doc/ble.md
- doc/buildAndProgram.md
- doc/gdb.md
- doc/jlink.md
Organized the readme.
Removed a broken article link.
Removed a few unnecessary notes.
Some flashing instructions were in separate documents and some were in buildAndProgram.md. They've all been moved to separate documents as a prerequisite for me to approve #801.
Other minor things.
> Docs reorganization

- src/displayapp/lv_pinetime_theme.c
- src/displayapp/lv_pinetime_theme.h
- src/displayapp/screens/StopWatch.cpp
- src/displayapp/screens/settings/QuickSettings.cpp
Remove unnecessary comments, styles, colors, overrides. Fix arc colors.
> Theme cleanup

- doc/contribute.md
Greatly simplified the contributing doc to make it a lighter read.
> Simplify contribute.md

- doc/coding-convention.md
Made the coding style doc lighter to read.
> Simplify coding style doc

- doc/code/Apps.md
Applist is in ApplicationList.h
The documentation mentioned to add a new App to ApplicationList.cpp. 
Currently the applications get added in a array in ApplicationList.h, clarified that.
> Updated Apps documentation

- src/components/motor/MotorController.cpp
> motorController: Fix infinite vibration on RunForDuration(0)

- src/displayapp/screens/CheckboxList.cpp
- src/displayapp/screens/CheckboxList.h
CheckboxList wasn't yet updated to use the new PageIndicator widget.
> Use PageIndicator in CheckboxList

- src/components/battery/BatteryController.cpp
- src/components/battery/BatteryController.h
- src/components/utility/LinearApproximation.h
This is a squash and combination of the PRs https://github.com/InfiniTimeOrg/InfiniTime/pull/1398 and https://github.com/InfiniTimeOrg/InfiniTime/pull/585 such that both contributions of @AlexXZero and @hassless will be part of the release changes
> AlexXzero and hassless: approximate battery discharge curve

- src/displayapp/screens/settings/SettingTimeFormat.cpp
- src/displayapp/screens/settings/SettingTimeFormat.h
- src/displayapp/screens/settings/SettingWakeUp.cpp
- src/displayapp/screens/settings/SettingWakeUp.h
- src/displayapp/screens/settings/SettingWatchFace.cpp
- src/displayapp/screens/settings/SettingWatchFace.h
This adds optimizations which are present on other settings screens to ones that are missing them.
> Settings screens optimizations

- src/CMakeLists.txt
I've rebased @jonvmey's PR #495, which tidies up the cmake file nicely.
> Cmake cleanup rebased

- docs/developer-documentation/index.md
pankajraghav changed his post to the subdomain blog
> Updated URL from  "Creating a stopwatch"

- .github/workflows/getSize.sh
- .github/workflows/main.yml
- docker/build.sh
Add workflow jobs that create and update a comment on PRs with the build size and difference from the base branch (develop).
It will not work on this PR, because develop doesn't contain the getSize.sh script.
Here's an example of the jobs in action https://github.com/Riksu9000/InfiniTime/pull/15
> Add buildsize workflow

- src/displayapp/screens/CheckboxList.cpp
- src/displayapp/screens/settings/SettingTimeFormat.cpp
- src/displayapp/screens/settings/SettingTimeFormat.h
CheckboxList was modified to hide the page indicator if there's only a single page.
> SetingTimeFormat use CheckboxList, reduce duplication

- src/displayapp/screens/List.cpp
Update settings list style. Keep yellow icons for a bit of spice.
> Gray settings list

- doc/contribute.md
**Requires #1514**
Cleaned up the list of things you can help with. Added a few points.
> Update contribute guide

- src/displayapp/screens/WatchFaceInfineat.cpp
- src/displayapp/screens/WatchFaceInfineat.h
- src/resources/fonts.json
Infineat was poorly optimized. This PR removes a lot of code and saves a lot of memory.
Fixed 12-hour mode, because the font didn't have the necessary characters.
> Infineat optimization

- src/displayapp/screens/Steps.cpp
Above is new, below is old. Fixes #1254
> Update steps UI

- README.md
Hi! Now that all the essential features are implemented, would you mind including WatchMate to the list of companion apps?
> Add WatchMate to the list of companion apps

- doc/buildWithVScode.md
Fixes #1585.
Link now points to the correct location.
> Fix Link in buildWithVScode

- src/displayapp/DisplayApp.cpp
- src/main.cpp
- src/systemtask/SystemTask.cpp
- src/systemtask/SystemTask.h
SystemTask should never write to the lcd.
> SystemTask: Move lcd to DisplayApp

- .gitmodules
- src/CMakeLists.txt
- src/components/ble/weather/WeatherService.cpp
- src/components/datetime/DateTimeController.h
- src/displayapp/DisplayApp.h
- src/displayapp/DisplayAppRecovery.h
- src/displayapp/screens/Clock.cpp
- src/displayapp/screens/SystemInfo.cpp
- src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
- src/displayapp/screens/WatchFaceDigital.cpp
- src/displayapp/screens/WatchFaceInfineat.cpp
- src/displayapp/screens/WatchFacePineTimeStyle.cpp
- src/displayapp/screens/WatchFaceTerminal.cpp
- src/displayapp/screens/settings/SettingSetDate.cpp
DateTimeController can provide everything we need. Depends on #1634.
> Remove date lib

- README.md
I changed my username and domain. This PR updates the ITD link in the README to match those changes.
> Update ITD link in README

- src/components/motion/MotionController.cpp
- src/components/motion/MotionController.h
Added lastX var to track the previous x acceleration for correct calculation of speed. 
Closes #927.
> ShakeWake: Fixed instant wake after sleep issue in certain positions

- src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
- src/displayapp/screens/WatchFaceCasioStyleG7710.h
label_battery_vallue > label_battery_value
> WatchFaceCasioStyleG7710: Fix Typo

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Check closed bugs

- .github/ISSUE_TEMPLATE/issue-report.yaml
> Prompt to check closed issues

- src/components/datetime/DateTimeController.h
- src/displayapp/screens/Timer.h
The two commits are not really related, but are of the "code quality / minor / do not change any behaviour" kind. Hope it is OK to package them in one pull request.
> Janitorial changes

- src/displayapp/DisplayApp.cpp
Instead of raw for loops use `std::ranges::transform` where possible.
And also use `std::ranges::find_if` instead of `std::find_if`.
> DisplayApp: use std::ranges function where possible

- .gitignore
Added files created from npm to .gitignore
> Ignoring npm files
