doc/buildAndProgram.md

Using the older (8.x.x) version of toolchain causes unexpected "template" errors, So we should always use version 9.x and above.

Update buildAndProgram : Use latest ARM-GCC toolcahain to build.

---

src/CMakeLists.txt

This fixes a minor mistake caused by an incomplete `message()` call I added.

Removed an incomplete message() call from CMakeLists.txt

---

src/graphics.cpp

This commit fixes upper/lowercase issues in directory names that cause
the build to fail on case sensitive file systems like Linux uses.

fix build on linux

---

src/drivers/Cst816s.cpp
src/drivers/Cst816s.h
src/drivers/TwiMaster.cpp
src/drivers/TwiMaster.h

Workaround for bug https://github.com/JF002/Pinetime/issues/79 until a better fix is found.
When the driver is stuck in an infinite loop for more than ~2.5ms, the TWI device is re-init and the transaction is retried.
Read() and Write() return an error code.

Workaround for TWI driver freeze

---

src/CMakeLists.txt

Without this change it attempts to flash using `pinetime-app.hex` (which doesn't exist) instead of `pinetime-app-${version}.hex` (which does exist).

Flash the correct file when running FLASH_pinetime-app with JLink

---

.github/workflows/main.yml

When installing Cmake you get Error: The add-path command is deprecated and will be disabled on November 16th...
And the file pinetime-mcuboot-app-dfu.zip was being generated as pinetime-mcuboot-app-dfu.zip.zip

Fix error install Cmake  main.yml

---

README.md

As it says on the tin... fixes some links broken during path changes in #68 ...

Fix companion app documentation links broken during #68

---

.gitignore
src/systemtask/SystemTask.cpp

Now when you wake up your watch you'll notice the correct time is waiting for you! The display would show the last time displayed for the amount of time it took to start advertising over BLE and wake peripherals. Note that I think the final change should be some restructuring but now the time updating on wakeup isn't annoying.

Reduced interval where the display shows the previous time on wake

---

doc/buildWithDocker.md
docker/amd64/Dockerfile
docker/arm64v8/Dockerfile

Docker files were:
Testing after resync with current develop branch:
Docker Hub images have been pushed... the AMD64 image automatically builds on changes to my fork/PR branch at present, and the ARM64v8 image was built and pushed from my Pinebook Pro. 
~~`build/` was added to `.gitignore`~~ No longer needed as was done in PR #124
As before, this is nearly ready to go, just going to let it simmer for a week before I take the draft status off.

Add docker hub image, and other tweaks to docker image and documentation

---

src/libs/lvgl/patches/0002-fix_bug_in_animation_management_for_lv_label.patch
src/libs/lvgl/src/lv_misc/lv_anim.c
src/libs/lvgl/src/lv_misc/lv_anim.h

In #152 and #163 , we noticed that the scrolling animation for labels was not working properly (text was scrolling really fast even with low specific speed, truncated strings,...).
According to [this link](https://forum.lvgl.io/t/animation-lv-label-long-sroll-lv-label-long-sroll-circ-stop-for-large-strings/1802), there is a bug related to animation speed in lvgl < 7.
I changed the animation time to uint16_t to uint32_t and tested with #163  : the whole text is displayed and the speed is not erratic anymore.
The patch is applied directly to the LVGL code (because the code is not a submodule, it's copied into this repo), and the .patch file contains the changes that were applied.

Fix bug in animation management for lv_label

---

src/CMakeLists.txt
src/FreeRTOSConfig.h
src/components/ble/HeartRateService.cpp
src/components/ble/HeartRateService.h
src/components/ble/NimbleController.cpp
src/components/ble/NimbleController.h
src/components/heartrate/Biquad.cpp
src/components/heartrate/Biquad.h
src/components/heartrate/HeartRateController.cpp
src/components/heartrate/HeartRateController.h
src/components/heartrate/Ppg.cpp
src/components/heartrate/Ppg.h
src/components/heartrate/Ptagc.cpp
src/components/heartrate/Ptagc.h
src/displayapp/Apps.h
src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h
src/displayapp/screens/ApplicationList.cpp
src/displayapp/screens/Clock.cpp
src/displayapp/screens/Clock.h
src/displayapp/screens/HeartRate.cpp
src/displayapp/screens/HeartRate.h
src/drivers/Hrs3300.cpp
src/drivers/Hrs3300.h
src/heartratetask/HeartRateTask.cpp
src/heartratetask/HeartRateTask.h
src/main.cpp
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

This PR adds support for the HRS3300 heart rate sensor. It's based on an open source implementation of the low-level driver and algorithm from [wasp-os](https://github.com/daniel-thompson/wasp-os) (thanks to [Daniel](https://github.com/daniel-thompson) for this great work!).
A new app is available in the menu and allows to start/stop the HR acquisition and displays the HR value.
A new BLE service (Heart Rate service) has been added and implements the standard BLE heart rate service.
Video : https://video.codingfield.com/videos/watch/63a5d374-f911-4eb5-88a1-4ee184205675

Heart rate sensor

---

src/components/battery/BatteryController.cpp
src/components/battery/BatteryController.h
src/displayapp/screens/BatteryIcon.cpp
src/displayapp/screens/BatteryIcon.h
src/displayapp/screens/Clock.cpp
src/displayapp/screens/Clock.h

This addresses #146 issue by averaging out the battery percent value. 
As a part of this PR, I have done the following changes: 
- Added a very simple circular buffer. I was thinking initially to use the `nrf_ringbuf`, but the API is very C-like and probably I don't need all the features that come with it. 
- Changed the percent value to be an `int` instead of a `float`. Floating-point arithmetic is generally more expensive and the user is not really interested in decimal level accuracy for battery percentage. I also noticed in many places where they are used, they are being downcasted to a smaller data type anyway. (e.g., see SystemInfo.cpp:50)
Tested it on the devkit. The battery variation reduced from +- 8% to +- 1%.

Fix erratic battery

---

doc/openOCD.md

Fixes a discrepancy with config file naming. The config files it tells you to create end in ocd, but the example flash command uses a filename ending in cfg

Fix config file discrepancy

---

src/drivers/St7789.h

Fixed minor error in commands enum for class St7789. The MemoryDataAccessControl was mistakenly set to `036` and should be `0x36`. 
I have built and run the app on my test PineTime but unsure how to do further validation and not sure why it wan't an issue (as `0x1E` is not a valid command) in the first place without doing further investigation.

changed command MemoryDataAccessControl from 036 to 0x36 in St7789 class

---

docker/build.sh

Goal: Don't run post-build.sh if the cmake build fail.

check for cmake build-success before running post-build.sh

---

.idea/codeStyles/Project.xml

This PR disables the space after pointer in declaration formatter until clang-format can do this formatting to avoid formatter fights, should there be any. The PR also specifies naming schemes, this allows enabling the linter warning that warns about inconsistent naming. 
Both changes are aligned to the current codebase.

Improve CLion's formatting rules

---

.clang-format

This PR adds a clang-format configuration file that will help unify formatting across different editors. 
Opens the possibility of a pre-commit hook that formats everything properly.
If this is merged, I can also make a PR to force using this instead of CLion's own formatter.

Added Clang formatting rules

---

.idea/codeStyles/Project.xml

This PR enables clang-format automatically in Clion, it depends on https://github.com/JF002/Pinetime/pull/194

Enabled clang-format in Clion

---

src/components/ble/HeartRateService.cpp
src/components/ble/NimbleController.cpp
src/components/heartrate/Ppg.cpp
src/drivers/Hrs3300.cpp

My OCD told me to fix this lol

Fix build warnings coming from HR implementation

---

src/displayapp/screens/Clock.h

Reworking of class DirtyValue inClock.h 
It makes no sense to have both a non-const lvalue-reference constructor overloaded with an rvalue-reference constructor.  You’ll only ever call the rvalue based on temporary objects and a const-lvalue-ref will also bind to an rvalue.
In addition, there is no ability to create a DirtyValue object without supplying an initialisation value forcing constructors to always take a value.
Finally, the Member-Initialisation-List (MIL) should always be used for value-initialisation  rather than using copy-assignment in the body of a constructor.
Proposed change:
Create default constructor and use NSMDI for type default initialisation
Replace lvalue and rvalue constructors with single const-lvalue-reference constructor
Use MIL for value initialisation
``` …
```

refactored class DirtyValue

---

src/CMakeLists.txt

Currently, trying to flash the firmware with `make FLASH_pinetime-app` fails because it's trying to flash `pinetime-app.hex`, which doesn't exist. The correct filename is `pinetime-app-0.13.0.hex`, which can be found in the EXECUTABLE_FILE_NAME variable.

Flash correct file name

---

src/CMakeLists.txt

The CMakeLists.txt files could do with improvement/refactoring. The current one has lots of redundant and incorrect usage of `-std=` which should be set using CMake directives.
C++14 is the first step towards supporting C++17 and all the major benefits that version brings. 
* C++14 is basically a bug fix for C++11 with over 400 defects fixed from C++11
* Binary literal, e.g. `0b01011010`
* Digit separators, e.g. `0b01'01'01'01`, `0xFFFF'83B0`, `1'000'000`
* `constexpr` for `std::array` - lots of opportunities to use `std::array` but have complete code elision
* `std::equal` can take two iterators, so arrays of unequal length can be compared
* Chrono-literals, e.g. `500ms`, `24h` `60min`
* `auto` and `decltype(auto)` function return types
* Generic lambdas, e.g. `[](auto p){}` - makes …

Refactored src/CMakelist to support C++14

---

src/displayapp/screens/Clock.cpp
src/displayapp/screens/Clock.h

The Clock.h had unnecessary private static functions and members. These should not appear in a header file as they increase couple and add complexity to understanding of the header.
These have been moved to an unnamed namespace in Clock.cpp to aim readability and maintenace.

Moved private statics into unnamed namespace in cpp file 

---

README.md

Instead of linking to the SVG, link to the GitHub Actions page of the project.

Fix README build-badge link

---

src/components/ble/MusicService.cpp
src/displayapp/screens/Music.cpp
src/displayapp/screens/Music.h
src/libs/lv_conf.h

- Enable LVGL animation (and disable groups, which were not used), and set the speed.
- Fix disc animation and progress display by initializing lastIncrement at 0 (a random value will be used otherwise, in release build)
Fix #97  and #130

Fix music app

---

src/components/ble/AlertNotificationClient.cpp
src/components/ble/AlertNotificationService.cpp
src/components/ble/MusicService.cpp
src/components/ble/NavigationService.cpp
src/components/ble/NotificationManager.cpp
src/components/ble/NotificationManager.h
src/displayapp/screens/Notifications.cpp

Add support for notification title. The notification buffer must contain the title and the message separated by a '\0' character.
If the buffer does not contain any \0, the whole buffer is considered to be the message of the notification. A default title will be displayed in the notification app.
Already tested with Amazfish:

WIP : Add support for notification title

---

docker/.gitpod.Dockerfile

Gitpod workspace path is based on repo name... it was `/workspace/Pinetime`, 
but after the repo rename it's now `/workspace/InfiniTime`. 
Also added second pip call as it's in the main dockerfile.

Gitpod workspace path update due to repo rename

---

.gitignore

It's a good practice to create a virtual environment for different projects that require Python.
This PR adds the most common Python virtual environment path to .gitignore.

Added Python virtual environment to .gitignore

---

tools/bin2c.py

Continuation of the failed #280

bin2c: Don't assume that the default Python version is higher than 2

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h
src/displayapp/DisplayAppRecovery.cpp
src/displayapp/DisplayAppRecovery.h
src/displayapp/screens/settings/QuickSettings.cpp
src/displayapp/screens/settings/QuickSettings.h
src/systemtask/SystemTask.cpp

Goal: Give a short vibration when vibrations are toggled on from the quick settings menu
Fix #271 
I don't have the battery connected to my devkit right now so I'm unable to test if the vibration is working. Perfect if anyone want to test it out for me. Otherwise this will have to wait until i receive my sealed devices.

Short vibration when enabling it in quick settings menu

---

src/displayapp/screens/WatchFaceDigital.cpp

* Show heartbeat icon in gray if the heartbeat sensor is turned off.
* Remove 'BPM' behind the value and '---' as placeholder. We don't have "steps" behind the steps either, so I think it looks more consistent and less cluttered.

Improve design of heartbeat data in digital watchface

---

doc/buildAndProgram.md

I had issues building InfiniTime for the first time because the instructions never mentioned needing these Python modules. Including them in the build documentation will help people not be confused like I was.
I recommend adding all needed modules to this list. I only added the ones I knew I was missing.

Add Python modules to build instructions

---

src/displayapp/screens/SystemInfo.cpp

First screen. Let the build date and build time string be centered as well as the others

SystemInfo app screen

---

.clang-tidy

This PR disables a check that is just an alias to an another one plus fine-tunes the cognitive complexity threshold for less noise.

Improved clang-tidy configuration for less noise

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h

DisplayApp::ReturnApp was inconsistently named, this PR fixes that. There's also a few small whitespace changes that have slipped in since the autoformat PR.

Fixed a naming inconsistency of DisplayApp::ReturnApp and a few formatting errors

---

src/displayapp/screens/Notifications.cpp

Long notification titles now scroll. Newlines get replaced with spaces to prevent the title being draw over the notification text

Notification title fix

---

CMakeLists.txt
docker/.gitpod.Dockerfile
docker/Dockerfile
src/Version.h.in
src/displayapp/screens/FirmwareValidation.cpp
src/displayapp/screens/FirmwareValidation.h
src/displayapp/screens/SystemInfo.cpp

I think this feature would be useful for developers.
These three commits quite independent
- first adds git package to docker image (for the people who use this build method)
- second adds `git rev-parse --short HEAD => PROJECT_GIT_COMMIT_HASH` in CMakeLists.txt
- and, finally, third adds the ability to show short ref on the SystemInfo app first screen and FirmwareValidation app screen

Feature: Store and show git short ref on PineTime alongside other firmware information

---

src/displayapp/screens/Navigation.cpp
src/displayapp/screens/Navigation.h

This PR slightly changes how `iconMap` is declared to reduce significantly the FLASH and RAM memory consumed by this app.
Before this change, `iconMap` was declare as a non-const member variable of Navigation. It means that this array was stored in FLASH. When Navigation was instantiated, the content of the flash was copied into RAM.
Also, `iconMap` was declared as `std::array<std::pair<std::string, const char*>, 89>`. Each item of the array was 28B long (24B for the string, 4B for the ptr to char). Using `const char*` instead of `std::string` frees 20B per element in the array.
Now, the array is declared as `static constexpr std::array<std::pair<const char*, const char*>, 86>` : 8B per element and it only lives in `.rodata` which is in FLASH. No need to copy it into RAM.
In the end, …

Navigation app: reduce memory usage

---

src/CMakeLists.txt
src/FreeRTOS/port_cmsis.c

Remove debug defines (DEBUG & DEBUG_NRF_USER) from the build. These defines can be useful for debugging purposes but not in production (release).
This reduces the size of the binary by about 6KB!
This also removes filepath that were embedded into the binary (.bin) file.

Remove debug defines 

---

cmake-nRF5x/CMake_nRF5x.cmake
src/CMakeLists.txt
src/displayapp/DisplayApp.cpp

Enable the following compilation flags:
* -fno-exceptions and -fno-non-call-exceptions : disable exception handling
* -fno-rtti : disable run time type information (needed by dynamic_cast, for example)
* -Os : optimize for size
These flags reduce the binary size by about 100KB!
Also, -fstack-usage generate debug info (not in final binary) to allow tools like Puncover to do a stack analysis.
#335 
#389
TODO:

Enable various compilation flags to reduce the binary size

---

src/displayapp/screens/SystemInfo.cpp

This will help the developers to size the memory buffer allocated to lvgl.
See https://github.com/JF002/InfiniTime/issues/313#issuecomment-850890064.

Add the maximum memory used by LVGL in SystemInfo app. 

---

src/drivers/SpiMaster.cpp

Fixes (presumably) unintentional case fallthrough in `SpiMaster.cpp`.
Closes #402

Fix fallthrough on case statement

---

src/displayapp/screens/SystemInfo.cpp
src/displayapp/screens/settings/Settings.cpp

Using make_unique avoids needing to repeat type information making it
less verbose. Also fixes clang-tidy warning modernize-make-unique.

Replace raw new expressions with make_unique

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/SystemInfo.cpp
src/displayapp/screens/SystemInfo.h

This PR turns sortById into a class method to avoid a name conflict.
There's also a dangling comment I removed, felt weird to make a separate PR for that.

Turned sortById to a class method to avoid a name conflict

---

src/components/ble/MusicService.cpp
src/components/ble/MusicService.h

I tried to separate these changes a bit more, but couldn't.
The PR makes some minor improvements to the music watchapp:
1) Switches to a macro for UUID generation. I think this might save some RAM+ROM, but primarily gets rid of all these hard-to-read assignments in the constructor.
2) Switches from C-style casts to reinterpret_cast
3) To avoid a name conflict, renames MSCallback to MusicCallback, also did a minor variable inlining (that the compiler will also do above `-O0` very likely)
4) `const`-ified the value getters for more safety
5) Moved a few functions around a tiny bit to group getters
(It should remain functionally identical, at least my tests with GB didn't show any differences)
Let me know if I should strip out some of these changes. 
I would also really like to know if the …

Used a macro for UUID generation, switched from C-style casts to reinterpret_cast, renamed callback

---

src/displayapp/screens/Clock.cpp
src/displayapp/screens/Clock.h

resolves #377 
this also allows Clock to just keep a single screen pointer instead of a ScreenList

Remove tap to switch Watchfaces

---

src/CMakeLists.txt
src/displayapp/Apps.h
src/displayapp/DisplayApp.cpp
src/displayapp/lv_pinetime_theme.c
src/displayapp/screens/ApplicationList.cpp
src/displayapp/screens/Metronome.cpp
src/displayapp/screens/Metronome.h

A simple app that triggers a vibration based on the user-selected beats per minute (closes #361).
What's done:

add basic metronome app

---

src/CMakeLists.txt
src/components/rle/RleDecoder.h

Fix compiler warnings present in `pinetime-recovery` and `pinetime-recovery-loader` build targets.

Warning cleanup

---

src/displayapp/screens/SystemInfo.cpp
src/drivers/St7789.cpp

This PR removes a few illogical lines from SystemInfo screen and the St7789 driver.
`batteryPercent` is cast to unsigned integer, the comparison is never true. The arguments in St7789 driver are both unsigned.

Removed an illogical comparison from SystemInfo and St7789 driver

---

src/BootloaderVersion.cpp
src/BootloaderVersion.h
src/components/ble/DfuService.cpp
src/displayapp/screens/SystemInfo.cpp
src/main.cpp
src/systemtask/SystemTask.h

This PR provide the following improvements:
- Extracts version exported by bootloader
- Displays bootloader version on System Info screen (Settings -> About menu)
- Enable SPI flash sleep mode if bootloader version >= 1.0.0
Unfortunately, I recently sealed my dev kit after flashing InfiniTime 1.0.0, so I would appreciate if someone with an open dev kit could help with the following tests:
- Is the reported bootloader version == 0.0.0 on watches with a bootloader older than 1.0.0 (before it exported its version in `NRF_TIMER2->CC[0]`)? Or is it a random value?
- Does this patch improve the power consumption of the watch when the screen is off? @vbelloir @nanch if any of you still have a setup to measure current in the μA range, I would love to have your feedback.
I'm also open to code …

SPI flash sleep if bootloader >= 1.0.0

---

.idea/codeStyles/Project.xml

This should improve naming convention checks and enable clang-tidy automatically.

Improved CLion configuration

---

src/displayapp/screens/Notifications.cpp

This fixes #305, where the buttons can move if the caller name is too long. Now the buttons are static, and outside of the container.

Fix call notification button alignment

---

src/components/ble/MusicService.cpp
src/components/ble/MusicService.h

@Avamander here are the changes I mentioned in #359 plus one or two other small improvements.
1. Eliminated the need for `reinterpret_cast<ble_uuid_t*>`ing by passing pointers to the first member of the UUID structs, which is a `ble_uuid_t`, instead of the struct itself.
2. Replaced the macro definitions for the UUID values with `constexpr` functions that return UUID objects directly and used those to initialize them. Also moved these variables to static values in the source file since that's the only place they're referenced.
3. Moved `MusicCallback` into the anonymous namespace since it's also only referenced inside of `MusicService.cpp`
4. Moved initialization of member variables with fixed constants to class declaration in the header and added explicit initializers for some …

Music service cleanup

---

src/displayapp/screens/FirmwareValidation.cpp
src/displayapp/screens/FirmwareValidation.h

Version and shortref info were spread out in four different labels. Here I combined them into a single label.

Condense firmware validation code

---

src/displayapp/screens/PineTimeStyle.cpp

The step gauge seems to have issues if the range is over 100, so this change sets the gauge range to 100 and calculates the step count as a percentage of the step goal to show progress.
Edit for a bit more context. Previously I was scaling the step gauge by adjusting the range, so a step goal of 13000 would make the range of the gauge 0-130, which resulted in only 9 divisions appearing. I'm not sure why this happened, but this fix changes the approach by setting the gauge range to 0-100 always, then calculating the needle position/progress as a percentage of the step goal.

PineTimeStyle step gauge bugfix

---

src/displayapp/screens/WatchFaceAnalog.cpp

Replaced the use of the standard library trig functions with a LUT-based
implementation instead. The standard library implementations produce
more accurate results but the usage here doesn't need that. This ends up
saving nearly 7kB of binary size.

Refactor trig functions into LUT

---

src/components/battery/BatteryController.cpp
src/components/battery/BatteryController.h
src/components/ble/BatteryInformationService.cpp
src/components/ble/BatteryInformationService.h
src/components/ble/NimbleController.cpp
src/components/ble/NimbleController.h
src/displayapp/screens/BatteryIcon.cpp
src/displayapp/screens/BatteryIcon.h
src/displayapp/screens/BatteryInfo.cpp
src/displayapp/screens/BatteryInfo.h
src/displayapp/screens/PineTimeStyle.h
src/displayapp/screens/SystemInfo.cpp
src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/screens/WatchFaceAnalog.h
src/displayapp/screens/WatchFaceDigital.h
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

Andreas from Gadgetbridge added support for notifications for battery level : https://codeberg.org/Freeyourgadget/Gadgetbridge/commit/603050b7cc30f6ef11ffaf73f3f88bf17a6922b6.
This will allow gadgetbridge (and other companion apps that supports it) to display the current battery level and update it with up to date values. Gadgetbridge also provides a graph of the battery level, low battery notification,...
InfiniTime just needs to send a BLE NOTIFY message when the battery level changes.

Notify battery level on BLE

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h

Makes displayapp run every 20ms more consistently by subtracting time spent executing from the next delay.
The simpler way to achieve the same results as #474. Whoops.

Adjust displayapp delay to compensate time spent

---

src/displayapp/DisplayApp.cpp
src/libs/lv_conf.h

After merging both #470 and #482, a new issue came up. LVGL would refuse to refresh in sync with displayapp, causing lag in some cases.
Here I fixed this issue by setting the refresh times in LVGL to 20ms.
The behaviour of the arc in Metronome has also changed with all these changes, ~~but it should be as intended now.~~
EDIT: There is still one more regression. In metronome, the dropdown menu can't be scrolled. Every value can still be reached by reopening the menu.

Set correct refresh times for LVGL

---

src/components/settings/Settings.h
src/displayapp/screens/settings/SettingWakeUp.cpp
src/displayapp/screens/settings/SettingWakeUp.h
src/systemtask/SystemTask.cpp

This PR should add the ability to set multiple wakeup sources.
Warning: I do not have a devkit, only a sealed one. I am not even sure that this compiles, so beware.
Also, does anyone know if there's a better way to know whether a checkbox is checked?
This would (try to) fix #277

Multiple wakeup sources

---

src/components/ble/DfuService.cpp
src/displayapp/DisplayApp.cpp
src/displayapp/screens/FirmwareUpdate.cpp
src/displayapp/screens/FirmwareUpdate.h
src/systemtask/SystemTask.cpp

Made the firmware update screen not exitable by the user. The screen closes automatically if an error occurs.
Added precautions to make sure the device doesn't sleep during firmware update.
Fixed bugs like State not resetting on error, and BleFirmwareUpdateFinished message being pushed before the Validated state was set.
Fixes #316

Make firmware updating more foolproof

---

hooks/README.md
hooks/pre-commit

In order to reduce forgetfulness when commiting code it's a good idea to have a pre-commit hook. This also creates the opportunity of creating a PR gate that checks that it is enabled.
This PR adds a simple pre-commit hook that autoformats files that are in a known safe location, that's why the relatively ugly regex. Just in case it also prints out that it is doing so. I also included a README in the folder with installation instructions.

Added a pre-commit hook that should simplify commiting pre-formatted code

---

src/displayapp/DisplayApp.cpp
src/displayapp/Messages.h
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

Dims the screen to lowest brightness two seconds before going to sleep. This gives time for the user to refresh the idle timer by tapping the screen if the watch is about to go to sleep.

Dim screen before sleep

---

src/displayapp/screens/SystemInfo.cpp

Show task state in systeminfo
R: Ready or running (Displayapp is probably always the one actually running)
B: Blocked
S: Suspended
D: Deleted
I: Invalid state

Add task state info to SystemInfo

---

src/displayapp/screens/Screen.h

There are at least three cases where Get() isn't used. This causes IsUpdated() to always return true, because the isUpdated variable is only set to false when Get() is run.
Instead of running dummy Get()s, I made IsUpdated() set the value to false. Now IsUpdated() works as expected returning true when the value has been updated between calls.
https://github.com/JF002/InfiniTime/blob/4f378e8726fdcff72598aa6ed12eeaa6b3e61355/src/displayapp/screens/WatchFaceAnalog.cpp#L198
https://github.com/JF002/InfiniTime/blob/4f378e8726fdcff72598aa6ed12eeaa6b3e61355/src/displayapp/screens/WatchFaceDigital.cpp#L238
https://github.com/JF002/InfiniTime/blob/4f378e8726fdcff72598aa6ed12eeaa6b3e61355/src/displayapp/screens/PineTimeStyle.cpp#L330

Fix cases where Get() from DirtyValue isn't used

---

src/displayapp/screens/Music.cpp
src/displayapp/screens/Notifications.cpp

After correcting LVGL time in #470, text scrolls much slower in Music and Notifications. they were set to scroll very slowly to compensate for LVGL running too fast. Removing the overrides makes the text scroll at a reasonable 25px/second, as defined in [lv_conf.h](https://github.com/JF002/InfiniTime/blob/d6cccc2dcd95a7d332ee657d1357ae060389f6e6/src/libs/lv_conf.h#L638).
Fixes #516

Fix slow scroll

---

src/components/datetime/DateTimeController.cpp
src/displayapp/screens/Clock.cpp
src/displayapp/screens/Clock.h
src/displayapp/screens/PineTimeStyle.cpp
src/displayapp/screens/PineTimeStyle.h
src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/screens/WatchFaceAnalog.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h

PR #232 by @nscooling is too old to be easily mergeable. I took most of the changes from this PR and applied them to analog and PineTimeStyle watchface too : 
- Replaced unnecessary sprintf statements with the build-in lvgl lv_label_set_text_fmt function (designed for that exact purpose)
- Cleaned up Clock construction and member-initialisation list, where the NSDMI can be used in preference (e.g. defaults zero values and nullptr)
- Cleaned up some logic code
- Change some instances of || to or (this is a C++ keyword, as is and and not and has been since the original C++98 standard)
- Ran Clock.* through clang-tidy based on .clang-format file at project root
- Replaced any remaining NULL with nullptr
- Replaced C-style casts with C++ casts
My apologies to @nscooling for not merging the …

Code cleaning in Clocks (analog, digital & PineTimeStyle)

---

src/main.cpp

If the device is reset while the i2c bus is used, the bus can get blocked. I suspect this might be what is causing the bootloop issue. Here I implemented code to attempt to unblock the bus. I don't know if this will actually fix the issue.
Bootloop issue #317
https://www.i2c-bus.org/i2c-primer/analysing-obscure-problems/blocked-bus/

Try to fix bootloop

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Metronome.cpp
src/displayapp/screens/Metronome.h

Clean up code.
Fix warnings.
Improve accuracy. It can still drift but much less than before. #571
Larger buttons.

Improve metronome

---

src/displayapp/screens/Music.cpp

Music OnTouchEvent() also returned the wrong value, which caused the touch to get ignored after #426.
Fixes #599.

Fix music app buttons

---

src/CMakeLists.txt

Add `-Wl,--print-memory-usage` to linker to show better FLASH/RAM size usage including %. This is based on linker scritp sections.

Add memory print usage in %

---

src/drivers/TwiMaster.cpp
src/drivers/TwiMaster.h
src/main.cpp
src/systemtask/SystemTask.cpp

Made using TwiMaster simpler. The bus is simply enabled on each read/write and disabled when done. There's no need to think about or control the state outside of TwiMaster. I don't know if this is more expensive, but it seems to work just fine.
Internal pullups were enabled. They're unnecessary because external pullups are used.
~~This will fix the freezing issue in #492 so I can finally move forwards with it.~~
Sleep() and Wakeup() can almost be made private, but there's still this piece of code in SystemTask I'm not brave enough to touch.
```
// Reset the TWI device because the motion sensor chip most probably crashed it...
twiMaster.Sleep();
twiMaster.Init();
```

TwiMaster rework

---

.github/workflows/main.yml

This fixes the github Action for Firmware building.
It is largely based on pull request #294 from nanch (which I critically reviewed).
There are a few small differences:
- Instead of using ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' for step "Install Embedded Arm Toolchain arm-none-eabi-gcc" instead the most current version (1.0.4) of fiam/arm-none-eabi-gcc is used, this now again works with the github automation (as I find this solution to be cleaner).
- Using cmake option -DBUILD_DFU=1 to build DFU and therefore removing the obsolete step
- Removing the unecessary step to build the firmware as this is also included in cmake and changing the unzip step to use the created zip-file. 
This is my first pull request ever, in case I should do something different next time, please provide me with …

fix Github Action build Firmware

---

src/displayapp/screens/settings/Settings.cpp

It's now over the 'Firmware' entry. It make sense to have 'Firmware' and 'About' the 2 last entries as they are the least used in my opinion.

Move PineTimeStyle settings up

---

README.md

Development documentation should be separated from user instructions.
Move getting started links higher and to a separate section so they're easier to find.
Replace section about PineTime with a link to pine64.org. Less information makes finding relevant information easier.
The "Using the firmware" (better name Companion apps) section should also be moved somewhere else, but where? Should they be in the same section as getting started?

Make README more friendly for new users.

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Notifications.cpp
src/displayapp/screens/Notifications.h
src/main.cpp

Remove unused variables in a couple of files.

Remove unused variables

---

src/CMakeLists.txt
src/components/ble/NimbleController.cpp
src/components/ble/NimbleController.h
src/systemtask/SystemTask.cpp

This is my WIP attempt to resolve the ble re-connect issue and get more reliable ble behavior. Comments, discussion, and suggestions are welcome. I'm testing on both my watch and dev-kit. The watch has been connected now for 3+ days. The dev-kit still fails periodically. I'm using both nRFConnect and GB for testing. I am (still) waiting on the breakout to connect my Segger JLink and gaze into the dumpster fire that is ble.
- Refactor ble advertising based on ble standards and conventions.
- Changes are based on the bleprph example code, bluetooth docs, and nimble docs.

Refactor ble advertising logic

---

src/components/motor/MotorController.h

Remove the unused include `app_timer.h` in `MotorController.h`
It still compiles. I haven't tested to flash it, as I only have a sealed watch, and I'm afraid to brick it

Remove unused include in MotoController.h

---

.github/workflows/main.yml

The documentation https://github.com/JF002/InfiniTime/blob/develop/doc/contribute.md#how-to-submit-a-pull-request-
tells us to make pull requests against `develop` branch.
Update the CI to run on those pull requests to have a check if the PR breaks something unintentionally.
Like https://github.com/JF002/InfiniTime/pull/126 but specifically for the develop branch, because a CI (Continuous Integration) should check the code continuously

Run CI on master and develop branch

---

src/displayapp/screens/Metronome.cpp

`xTaskGetTickCount()` returns a `TickType_t`, which is defined as an
`uint32_t`. This is compared to the `bpm` variable, which is a `int16_t`
in the range of 40 to 220 as defined in the constructor.
```cpp
lv_arc_set_range(bpmArc, 40, 220);
```
Just to be sure also add an assert that `bpm` is greater than 0, as this
would result in a division by zero or negative values, which would
unintentionally underflow to a very large number.
---
Not flashed, I have only a sealed watch and I'm afraid of bricking it

Fix unsigned/signed comparison warning in Metronome.cpp

---

src/components/ble/NotificationManager.cpp
src/components/ble/NotificationManager.h
src/components/motor/MotorController.cpp
src/components/motor/MotorController.h
src/components/settings/Settings.h
src/displayapp/screens/Notifications.cpp
src/displayapp/screens/settings/QuickSettings.cpp
src/main.cpp
src/systemtask/SystemTask.cpp

This makes the button with a bell icon disable notifications instead of disabling vibrations. This makes Timer and Metronome work correctly when notifications are disabled. When disabled, the watch won't wake up when receiving notifications and will show an icon on the watch face indicating a new notification. This was always present, but wasn't ever shown.
Fixes #637
Related to #610, because now the notification screen won't pop up when notifications have been disabled.
Inspred by #662 so that we wouldn't need a `StartRingingDisregardSettings()` function.

Toggle notifications only, keep vibrations.

---

src/libs/mynewt-nimble/nimble/controller/include/controller/ble_ll_rfmgmt.h

The previous code always returned 0 (when `MYNEWT_VAL_BLE_LL_RFMGMT_ENABLE_TIME` is not defined), rather than a time near to the current tick.  This caused an issue in at least one place: `ble_ll_adv_sm_start()`, where the calculation of `delta` overflows when the system timer is at 0x80000000 or above -- causing an incorrect, huge adjustment to be made to the scheduled time, ultimately stopping adverts from being sent.
This returns the current time as the time at which the RF will be fully enabled.  
This fixes the advertising issue described in the comments under Issue #302 (although the issue itself might be about broader connectivity problems).

Fix advertising packets stopping after 18.2 hours

---

src/components/fs/FS.h

Unless I've made a mistake in my understanding, I think the current filesystem size has a typo and is too large.  
I think it should be (0x400000 - 0x0B4000 =) 0x34C000, but is currently 464kB larger than this.  Writing data to the filesystem will eventually attempt to write past the end of the memory.
I'm not sure whether SPINOR memory would wrap back to the start (whether it ignores the high bits of the address).  If it does, perhaps the driver should additionally check the range to prevent accidental modification of the bootloader assets?

Fix the size of the filesystem.

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h

`lv_task_handler()` returns the time in ticks to the next task it needs to run.
This can now be used now that DisplayApp isn't locked to a certain refresh period to refresh apps consistently. #497
Using this time as the queueTimeout is more accurate, as messages can still cause slight delays. This also makes it possible to have tasks that run even more often than the refresh period.

Let LVGL control queueTimeout

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml

This is an example of what can be done with issue template forms in Github. With some autolabelling and a form structure it might be possible to get better structured bug reports and feature requests and avoid duplicates.
Feedback on existing or new templates appreciated.
_I haven't included PR templates but those are an option as well._

Issue templates to tame the wilderness

---

src/displayapp/DisplayAppRecovery.h

Fix the "recovery" firmware build targets
Error introduced in #746

Fix recovery firmware build

---

src/displayapp/screens/SystemInfo.cpp
src/displayapp/screens/Twos.cpp

Memory savings by replacing strings

---

src/drivers/Cst816s.cpp
src/drivers/Cst816s.h

I noticed that I couldn't get 100% reliable readings from the CST816S (touch controller) (see https://github.com/InfiniTimeOrg/InfiniTime/issues/763#issuecomment-962436976). I added a few checks in `Cst816S::GetTouchInfo` to ensure it only returns is data are valid. I also added a retry functionality for the Check ID procedure. It'll hopefully reduce the number of false positive when checking the device IDs.
This PR might fix #763, but I think we still have other issues with I²C (see https://github.com/InfiniTimeOrg/InfiniTime/issues/763#issuecomment-962489299).
Anyway, it would be nice if some people could test that PR and ensure it does not show the warning about an incompatible touch controller. @Arsen6331 @geekbozu @kieranc I would be really interested to know if this PR fixes that …

Add data validity check and retries in CST816S driver

---

src/displayapp/screens/Alarm.h

Fixes #770 
This should be fixed before releasing 1.7.0

Fix Alarm app crashing on buttonpress

---

CMakeLists.txt
src/drivers/Cst816s.cpp

This issue was reported [on twitter](https://twitter.com/meanmicio/status/1459558057655029761?s=20) just after the release of 1.7  the touch panel is completely unresponsive after the update of 1.7. It works fine when reverting to 1.6.
I built a [quick'n'dirty fix for Luis to test](https://github.com/InfiniTimeOrg/InfiniTime/tree/debug-touch-luis). This fix disables all the new checks we added in 1.7 to make the touch driver more reliable : it works!
The chip IDs reported by the chip are `b4.69.2` instead of the expected `b4.0.1`
So, we'll have to investigate why the IDs are different, but, as the touch panel is working fine, I assume this is "normal".
In the meantime, we can release a fix for this issue : when working on 1.7, we added a warning message that would be displayed when …

Fix unresponsive touch panel after update to 1.7

---

src/displayapp/screens/BatteryInfo.h

Those two includes are not used. The project still compiles without them.
Not tested on PineTime, just compiled

BatteryInfo: remove unused FreeRTOS.h and timer.h includes

---

src/displayapp/DisplayApp.cpp

Add extra handling when in adjacent screens to use the most fitting animation.
Fixes #817

Fix animation when long pressing on screens adjacent to watch face

---

src/displayapp/screens/SystemInfo.cpp

Removed Steps which is hard coded to display 0.
Could be misleading and is using up memory.

About : Remove misleading info

---

src/displayapp/screens/PineTimeStyle.h

Remove unused `ScreenList.h` include and add a forward declaration for
the `MotionController` class.

PineTimeStyle: remove include and add forward declare

---

src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h

The header has an extra unused `ScreenList.h` include.
And the `cpp` file needs a `Settings.h` include. The header uses a forward declaration for it, but the `cpp` file needs the real include.

Watchface digital include cleanups

---

src/components/settings/Settings.h

The include for `drivers/Cst816s.h` isn't used in `Settings.h` and `Settings.cpp`
Tested only compiling, not on actual device

Settings: remove unused driver include

---

src/displayapp/screens/Metronome.h

Metronome class inherits from Screen, but the `Screen.h` include is missing

Metronome: add missing include for Screen.h

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/InfiniPaint.cpp
src/displayapp/screens/InfiniPaint.h

This is a very simple pull requests that changes the Paint app in order to vibrate on color change (because It's hard to know if the touch controller actually registered a long press or a small swipe). I also fixed the logic for the color rotation. Before, the color magenta was unreachable and instead black was chosen a second time. The `color`  variable was changed to initialize to 3 instead of 2, so you don't have to press twice on the first rotation.

InfiniPaint vibrate on colorchange, fix color rotation

---

src/displayapp/screens/Paddle.cpp

To make the game a bit more challenging an less predictable add a little
bit of randomness to the `dy` value. When hitting the right wall add a random
number (one of [-1, 0, 1]) to the `dy` value.
To keep the difficulty level managable limit the dy value to be in the
range from -5 to 5.
Tested on `lv_simulation` branch #743 not on actual hardware

Paddle: add a little randomization in the dy speed

---

src/displayapp/screens/Clock.cpp

Add missing include in `Clock.cpp` for `Settings.h`. The Settings class
is forward declared in the header file, but it needs to be included in
the cpp file.

Clock: add missing Settings include

---

src/systemtask/SystemTask.cpp

System task getting a GoToSleep event will not respect doNotGoToSleep and attempt to sleep anyway.

Adjust systemtask to respect doNotGoToSleep.

---

src/buttonhandler/ButtonHandler.cpp

FreeRTOS says zero is not a valid value for xTimerPeriodInTicks.
Zero value fires an assertion on line 361 in timers.h

Fix assertion failure in ButtonHandler

---

src/displayapp/screens/PineTimeStyle.cpp
src/displayapp/screens/PineTimeStyle.h

This PR fixes a few minor issues with the PineTimeStyle watchface
- The rectangle behind the time digits started 5px from the left edge of the screen
- The initial time digits of 12:34 had the potential to cause alignment issues
- The notification and bluetooth icons now work as I originally wanted, if only one icon is visible, it is centered below the battery icon, if 2 icons are visible, they go side-by-side.

PineTimeStyle alignment fixes

---

src/touchhandler/TouchHandler.h

FreeRTOS and task.h aren't used in the Header file. Furthermore the
SystemTask forward declaration isn't needed as it isn't used in the
header.

TouchHandler: remove unused FreeRTOS.h and task.h includes from header

---

src/CMakeLists.txt
src/displayapp/lv_pinetime_theme.c
src/displayapp/screens/Styles.cpp
src/displayapp/screens/Styles.h
src/displayapp/screens/settings/SettingDisplay.cpp
src/displayapp/screens/settings/SettingDisplay.h
src/displayapp/screens/settings/SettingTimeFormat.cpp
src/displayapp/screens/settings/SettingTimeFormat.h
src/displayapp/screens/settings/SettingWatchFace.cpp
src/displayapp/screens/settings/SettingWatchFace.h

Some checkboxes act like radio buttons. Update the style to match the behaviour.
Also create checkboxes in loops.

Style checkboxes as radio buttons

---

src/displayapp/DisplayApp.cpp

Add missing break statement - AlarmTriggered case falls through to ShowPairingKey case

FIX: AlarmTriggered fall through to ShowPairingKey

---

doc/BLEFS.md
doc/ble.md

This PR adds documentation for the BLE side of the BLE FS protocol, as implemented in #756, and will be updated with the mentioned PR.

Add documentation for BLE FS

---

src/components/ble/BatteryInformationService.cpp
src/components/ble/NimbleController.cpp
src/components/ble/NimbleController.h

Support passkey pairing when requested by the central.
Also, fixes a comment and a reorder warning introduced by a faulty conflict resolution.

Optional secure pairing with a passkey

---

src/displayapp/screens/WatchFaceDigital.cpp

When you're on a bright sunlight, then the blue BLE icon is not easily visible on black background. This is more important when I ride a bike and phone is in my backpack so I could easily check whether I'm connected and don't miss notifications.
I like colorful LCD display but in practice the white text is the most readable.
Similar ui PRs/issues:
#540 
#555

Set BLE icon on WatchFaceDigital to brighter color to better see on sunlight

---

src/CMakeLists.txt

I think that the nRF SDK is fine to optimize as much as possible because it's IMO the most speed-sensitive (ISR, logging etc.) part of InfiniTime besides NimBLE.
I've also disabled a warning we can't fix, this significantly cuts down clutter coming from that module.

Enabled stronger optimizations on nrf-sdk and disabled a warning

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Metronome.cpp
src/displayapp/screens/Metronome.h
src/displayapp/screens/Music.cpp
src/displayapp/screens/settings/QuickSettings.cpp

Metronome can be closed by swiping down from the center. I could make it not close while dragging the arc, but I couldn't make it not close while dragging the dropdown menu, so this is the next best thing.
Music app shows volume buttons on swipe up and swiping down goes back to next/prev. now swiping down in the default state will close the app.
Flashlight can now be closed by swiping down. Also the transitions animation was changed to match other apps and returnapp is quicksettings instead of watchface.
The last apps that can't be closed through the touchscreen are Paint, Paddle and Twos, but they can't easily be made to use swipes for closing, so they would need some other solution.
Closes #651, unless we keep it open for these three. …

Improve gesture consistency across the firmware

---

.github/workflows/main.yml

By switching the CI/CD workflow to use CMake's `ninja` backend, the build time goes down considerably compared to GNU Make:
| | ninja | make |
| ----- | ----- | ---- |
| non-cached | ~5 min. | ~8 min. |
| cached | ~2 min. | ~4.5 min. |

Switch CI/CD to build using ninja vs. make

---

src/components/motion/MotionController.cpp
src/components/motion/MotionController.h
src/displayapp/screens/Steps.cpp
src/displayapp/screens/Steps.h

Fixes #694 
- Added a lap button (similar to the lap button in Stopwatch) to reset the step counter.
- Added a total step count in that does not get reset in the bottom right corner.
- Moved/shrank existing Steps UI to fit the new button and total step count
- Added a variable to MotionController to save the steps since the last lap.
Note that using the lap button does not reset the progress to the daily step goal. The progress bar uses the total step count.
The image below demos the new button after fresh boot with (1) 0 steps, (2) the watch after taking some steps (step count and total updated and equal), (3) pressing the lap button (step count reset, no change to total), and (4) after walking again (step count and total updated, but not equal).
I also checked that large step counts do …

Added Trip meter to Steps app

---

src/CMakeLists.txt
src/components/motion/MotionController.cpp
src/components/motion/MotionController.h
src/components/settings/Settings.h
src/displayapp/Apps.h
src/displayapp/DisplayApp.cpp
src/displayapp/screens/settings/SettingShakeThreshold.cpp
src/displayapp/screens/settings/SettingShakeThreshold.h
src/displayapp/screens/settings/SettingWakeUp.cpp
src/displayapp/screens/settings/SettingWakeUp.h
src/displayapp/screens/settings/Settings.cpp
src/systemtask/SystemTask.cpp

Adds shake to wake by calculating Y/Z acceleration. Essentially a gentle wrist flick action will turn the screen on.
I think its set to be a hair over sensitive as of the moment.  Looking for some feedback there. In the long run I want to break out a settings option to select how sensitive it is, but not there yet.
.

Shake wake [User Feedback Required]

---

src/displayapp/screens/settings/Settings.cpp

Added an icon and renamed to Shake Calib., so that it's more clear this only affects shake wake.

Update shakewake menu option

---

src/displayapp/screens/PineTimeStyle.cpp
src/displayapp/screens/PineTimeStyle.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h

Simplify time displaying.
Use `lv_label_set_text_static()` where possible.
Use `lv_obj_realign()` where possible.

PTS and digital watchface code cleanups

---

src/systemtask/SystemTask.h

`QueueHandle_t` is used in header, but there is no forward declaration, so including the right `queue.h` header

SystemTask: add missing queue.h include for QueueHandle_t

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Notifications.cpp
src/displayapp/screens/Notifications.h
src/systemtask/SystemTask.cpp

Notification preview now disables sleep, so the preview can be longer than 5s without the display timing out first.
Notification timeout is now set to 7s
Call notification now also uses the preview timeout, so it will stop ringing after 7s.
The timeout can now be cancelled by tapping on the screen.
Added ReloadIdleTimer() to the SystemTask message EnableSleeping to restart the idle timer when there is no user interaction.
Made pressing the call buttons exit the notification screen, like they used to.

Improved notification timeout

---

src/drivers/Hrs3300.cpp
src/drivers/Hrs3300.h
src/heartratetask/HeartRateTask.cpp

changed low level driver for HRS3300 to return uint32_t values (since it gives 18 bit values) 
and changed hidden uint16_t to float convert, to a static_cast.
supersedes #875
thanks for all the great work!

Hrs driver changes

---

src/drivers/Hrs3300.cpp

TL/DR Heart rate sensor doesn't work for me, its random. Changed HRS gain from x64 to 4x and now it works much better. However I don't know if this is good/proper value, so I created a setting to let everyone customize it.
So as for few other people ( https://forum.pine64.org/showthread.php?tid=13727 and https://github.com/JF002/InfiniTime/issues/397 ) heart rate sensor was not working for me. Actually it wasn't working at all, I could leave the clock on the desk and the desk would have pulse ranging from 40 to 220. To me it was completely random no matter if I had it on hand or not. Though it seems like some folks have it working about fine, so it probably depends on something.
Checking documentation from here: http://www.tianyihexin.com/pic/file/20170627/20170627154877337733.pdf I've …

Heart rate sensor - HRS gain changed to x8

---

src/displayapp/screens/Music.h

In the first `Music::Refresh` call the lastLength and totalLength are
not initialized. The `lastLength` value is read first from the
musicService. Naturally in the first itereation that is changed and
`UpdateLength()` is called. There the variable `totalLength` is used as
well, but that variable isn't initialed to a sensible value yet. This
leads to sometimes the `Music.h` screen segfaulting (depending on the
random uninitialized data in the `lastLength` variable)

Music: initialize totalLength to have non-random data from the start

---

src/components/datetime/DateTimeController.cpp
src/systemtask/SystemTask.cpp

The alarm needs to be rescheduled when the time has been changed.
Also the SystemTask message `OnNewTime` was never sent, so now it is sent when the time is set.
Fixes #774

Fix alarm on time change

---

doc/ui_guidelines.md
src/displayapp/lv_pinetime_theme.c
src/displayapp/lv_pinetime_theme.h
src/displayapp/screens/Alarm.cpp
src/displayapp/screens/Alarm.h

I tried to create a checkable button design in #973, but wasn't totally happy with it, so I changed it to a switch here anyway. This is better, because it uses a design people are already familiar with instead of creating something new.
EDIT: The alert layout doesn't need to be changed, so I reverted that change. The adjustment buttons don't need to be visible during alerting, but that's for another PR.

Alarm: Change checkable button for a switch

---

src/systemtask/SystemTask.cpp

The static_cast syntax requires brackets around the input variable. The
implementation worked because the used input are defines, which add the
missing brackets like the following:
```cpp
#define GPIO_PIN_CNF_SENSE_Low (3UL)
```

SystemTask: fix static cast missing brackets syntax

---

src/components/datetime/DateTimeController.cpp
src/components/datetime/DateTimeController.h
src/components/settings/Settings.h
src/displayapp/screens/Tile.cpp
src/displayapp/screens/settings/QuickSettings.cpp
src/main.cpp

This makes the status bar display time in the correct format per the "Time format" setting.
New function is added to DateTime called FormattedTime returns a string with the correct time format, so the caller doesn't need to check the settings directly.
I had to remove one unused include from Settings.h to avoid circular include problems.
This is a scaled-back version of #786 (per @Riksu9000 's suggestion) to fix the time display while thinking about how to handle other changes to the status bar.

Status bar displays time in 12 or 24 hour format based on settings

---

src/systemtask/SystemTask.cpp

Remove unused includes. The firmware still compiles fine without the includes.

SystemTask: remove unused ble includes

---

src/components/motor/MotorController.h
src/displayapp/screens/Notifications.cpp
src/displayapp/screens/Notifications.h

We get the motorController object, so store and use it.
It's the only usage of the class function `StopRinging()` instead of using on the member function

Notifications: use motorController object instead of class function

---

src/displayapp/screens/settings/SettingShakeThreshold.cpp
src/displayapp/screens/settings/SettingShakeThreshold.h

SettingShakeThreshold.h uses SystemTask, but doesn't include the header.
Fixing that for the simulator.
For consistency make the header include a relative to src include.

SettingShakeThreshold: add missing SystemTask.h, relative include

---

src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

SystemTask.h included BatteryController.h, and BatteryController.h
included SystemTask.h. If unlucky the class SystemTask isn't created yet
when BatteryController wants to use it.
Fix that cyclic dependency by forward declaring the BatteryController
class and including it in the SystemTask.cpp file, where it is needed.

SystemTask: forward declare BatteryController to fix of cyclic dependency

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h
src/displayapp/DisplayAppRecovery.cpp
src/displayapp/DisplayAppRecovery.h
src/main.cpp

For the simulator I need a way to get to the brightnessController object
and handle the set brightness-levels accordingly.
This is done by the constructor expecting a brightnessController object
instead of initializing one itself.
If this change is too intrusive adding a function like `getBrightnessLevel()` to just the main `DisplayApp.h` forwarding the brightness level of the internally stored `BrightnessController` would be another way forward for me.
Or return a reference with `getBrightnessController()`

Provide reference to BrightnessController in DisplayApp

---

src/displayapp/screens/HeartRate.h
src/displayapp/screens/Motion.h

The include `bits/unique_ptr.h` isn't used, so remove it.

Remove unused includes in HearRate and Motion.h

---

src/displayapp/screens/Notifications.cpp
src/displayapp/screens/Notifications.h

The variable `title` is defined as `const char*`, which means, that
`strchr()` returns a `const char*` as well according to
https://www.cplusplus.com/reference/cstring/strchr/
But in the same line the return value is assigned to a non-const
`char*`, which shouldn't be allowed (error with `-pedantic`).
To prevent manual memory management just use `std::string` to copy the
provided title and replace newlines in the copied string.

Notifications: replace newlines in label-copy instead of const char* title directly

---

src/displayapp/screens/settings/Settings.cpp

This PR replaces the generic list icon in the Airplane Mode settings entry with a more fitting one

Replace Airplane mode icon

---

src/displayapp/screens/WatchFaceTerminal.cpp
src/displayapp/screens/WatchFaceTerminal.h

The battery icon is redundant and the power icon can be replaced by "Charging" text. Also tweaked some label functions.

terminal watchface: remove icons and other fixes

---

src/components/settings/Settings.cpp

For each filesystem interaction be more specific if we want to read from
the file or write to it.
Doing a non-creating read on the loading of the settings file, otherwise
an empty file could be created, and when reading that empty file for the
initial settings I would expect an error (or random data) when reading.
I found this, trying to create a simulator for the file-access. Maybe I'm not understanding how `littlefs` works, but for me it seems like this should be an issue for the first read of the `settings.dat` file
---
Not tested on an actual device

Settings: more specific read and write mode

---

src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/screens/WatchFaceDigital.cpp

closes #966 
as discussed there, (and as seen in a quick test) the `SetClockFace` is not needed.

removed SetClockFace from watchface Constructors

---

src/CMakeLists.txt
src/components/ble/AlertNotificationClient.cpp
src/components/ble/DfuService.cpp
src/components/ble/HeartRateService.cpp
src/components/ble/MotionService.cpp
src/components/ble/NimbleController.cpp
src/systemtask/SystemMonitor.cpp
src/systemtask/SystemMonitor.h
src/systemtask/SystemTask.h

No need to implement `SystemMonitor<FreeRtosMonitor>` if the variable
`configUSE_TRACE_FACILITY` is set to `1`. Otherwise implement the
`DummyMonitor` class.

SystemMonitor: implement FreeRtosMonitor only if trace facility is set

---

.github/workflows/lv_sim.yml
README.md

Add simulator to have pinetime Screens on PC for development.
The first Screen can be run locally, using your mouse to play Paddle.h!
based on lvgl 8 port #734 
lv_sim based on: https://github.com/lvgl/lv_sim_eclipse_sdl
---
2021-11-03 updated screens with PineTime fonts
---
2021-11-07 new Screen Metronome and the first simulated external: MotorController (shown by red dot)
---
2021-11-15 new Screen `BatteryInfo.h` with a very low Battery, according to the `BatteryController.h` stub
---
2021-11-28 rebased on `develop` branch getting the new `v1.7.1` version of `FlashLight.h`
---
2021-11-30 All three PineTime Watch Faces are working now: `WatchFaceDigital.h`, `WatchFaceAnalog.h` and `PineTimeStyle.h`
---
2021-12-02 Can trigger a Notification, got the system time, and the first …

Lvgl simulation run PineTime screens on your PC

---

src/displayapp/screens/settings/SettingChimes.h

There are 3 options, but the array-size is set to 2. This leads to
memory corruption in the initialization of the SettingChimes screen when
assigning the third option object pointer.
Found in https://github.com/InfiniTimeOrg/InfiniSim/issues/11 by @edo0

Fix SettingChimes cbOption array size

---

src/components/datetime/DateTimeController.cpp
src/components/datetime/DateTimeController.h
src/displayapp/screens/WatchFaceAnalog.h

`MonthShortToString` and `DayOfWeekShortToString` don't change theunderlying object. Those are just getters and can be declared `const`.
With the getters const we can store a const reference in `WatchFaceAnalog`

Datetime const and analog const ref

---

src/displayapp/screens/Twos.cpp

We have a comparison like `if (( a == b ))`, which is a parenthesis too
much, which generates the following warning
```
InfiniTime/src/displayapp/screens/Twos.cpp:133:35: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
if ((grid[newRow][newCol].value == grid[oldRow][oldCol].value)) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
InfiniTime/src/displayapp/screens/Twos.cpp:133:35: note: remove extraneous parentheses around the comparison to silence this warning
if ((grid[newRow][newCol].value == grid[oldRow][oldCol].value)) {
~                           ^                            ~
```

Twos: fix warning about extra paranthesis

---

src/displayapp/screens/Music.h

Clang warns on `OnTouchEvent()` function, which is overridden, but is
missing the `override` keyword
```
In file included from InfiniTime/src/displayapp/screens/Music.cpp:18:
InfiniTime/src/displayapp/screens/Music.h:43:14: warning: 'OnTouchEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
bool OnTouchEvent(TouchEvents event);
^
```

Music: fix warning about overridden function

---

src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/screens/WatchFaceAnalog.h

Use local date and time variables. No need to store them in the object.

WatchFaceAnalog: local date/time variables

---

src/components/ble/MusicService.cpp

This should work around this bug : https://github.com/InfiniTimeOrg/InfiniTime/issues/825 and prevent heap over-allocation.

Limit the size of the track and album name received by MusicService.

---

src/FreeRTOSConfig.h
src/components/ble/NimbleController.cpp
src/libs/mynewt-nimble/porting/npl/freertos/src/nimble_port_freertos.c
src/systemtask/SystemTask.cpp

In current configuration, the timer task (the one from FreeRTOS) has the lowest priority (0). Both display and system tasks are also set on priority 0.
In cases where any other task takes too much time to execute (it can happen in Display Task, see https://github.com/InfiniTimeOrg/InfiniTime/issues/825), the timer task does not have the opportunity to run fast enough to detect and debounce presses on the button.
This commit sets the following priorities:
- [0] : Display  Task
- [1] : Timer and System tasks
- [2] : BLE Host
- [3] : BLE LL
This way, we ensure that button presses will always be detected, even if the rendering of the display takes a huge amount of time.

Fix task priorities to ensure that button presses are correctly detected

---

src/displayapp/DisplayApp.cpp

In display app, call the event handler of the current app before loading the new one. This way, we ensure that lv_task_refresh() is called before sending event to the newly loaded app.
Fix #1023

Fix app loading and event management in DisplayApp

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Timer.cpp
src/displayapp/screens/Timer.h

Fixes #445
This display was "corrupted" because the app do not have a background label that cover the whole screen. Because of that, LVGL would not refresh the whole display at once, but would refresh it in 3 non consecutive parts, which confused the HW scrolling transition.

Fix display corruption when the timer is triggered

---

src/displayapp/DisplayApp.cpp
src/systemtask/SystemTask.cpp
src/touchhandler/TouchHandler.cpp
src/touchhandler/TouchHandler.h

Let the TouchHandler::GestureGet() function return a TouchEvent instead
of the touchpanel-driver specific enum.
This helps to move the driver specific helper function `ConvertGesture`
from `DisplayApp` into `TouchHandler`.

Let TouchHandler return TouchEvents instead of driver specific enum

---

src/components/alarm/AlarmController.cpp

Allow a loss of precision if the system clock has a lower resolution
than nanoseconds. This is the case for webassembly.

AlarmController: allow loss of precision for alarmTime cast

---

src/drivers/SpiNorFlash.h

`SpiNorFlash.h` is a C++ header, but the `Identification` struct is
created in a C style using `typedef struct`. Clang issues a warining
about this discrepancy:
```
In file included from /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/systemtask/SystemTask.cpp:13:
/home/nero/repos/pinetime/InfiniSim/sim/drivers/SpiNorFlash.h:16:21: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct __attribute__((packed)) {
^
Identification
/home/nero/repos/pinetime/InfiniSim/sim/drivers/SpiNorFlash.h:17:9: note: type is not C-compatible due to this default member initializer
uint8_t manufacturer = 0;
^~~~~~~~~~~~~~~~~~~~
/home/nero/repos/pinetime/InfiniSim/sim/drivers/SpiNorFlash.h:20:9: …
```

SpiNorFlash: use C++ style struct in C++ only header

---

src/displayapp/screens/Timer.cpp

Make Alarm and Timer layouts the same.
Also made the start button 50px tall, since every other button on the bottom edge is 50px tall.
Fixes #924

Fix Timer layout

---

src/displayapp/screens/StopWatch.cpp
src/displayapp/screens/StopWatch.h

`calculateDelta()` isn't necessary, because `TickType_t` handles overflow naturally.
Use centiseconds in a conversion function instead of milliseconds, so the math uses smaller numbers and the last digit wasn't used anyway.
Other small fixes.

Stopwatch fixes

---

src/displayapp/screens/Paddle.cpp

As suggested in https://github.com/InfiniTimeOrg/InfiniTime/issues/1062
in point 3. The paddle should be kept on screen and not travel out of
the screen boundaries.
@Danimations I couldn't resist :grin:

Keep the paddle on screen in whole

---

src/components/timer/TimerController.cpp
src/components/timer/TimerController.h
src/systemtask/SystemTask.cpp

I read that this would be preferred, as app_timer is an nrf specific feature.

Replace app_timer with FreeRTOS timers in TimerController

---

src/displayapp/screens/List.h

List.h uses `std::array` as container, but is missing the `<array>`
include. Add it to make the header self contained.

List: add missing array include

---

src/displayapp/DisplayApp.cpp
src/drivers/St7789.h

DisplayOn() and DisplayOff() are direct lcd commands, it's better to use only Sleep() and Wakeup().
The lcd is already controlled in SystemTask, so these aren't necessary in DisplayApp. SleepIn() puts the lcd into the lowest power mode so DisplayOff() doesn't do anything as far as I can tell.
EDIT: lcd can't be removed from DisplayApp, because DisplayAppRecovery needs it, and DisplayAppRecovery also has a lot of unused parameters. I'll look at this separately.
This eliminates the mysterious 500ms delay that exists in DisplayOff(). https://github.com/JF002/InfiniTime/blob/6f9f0e8b0e42a5526d47ca664534fb6b0ccb6ace/src/drivers/St7789.cpp#L119

Improve sleep time

---

src/displayapp/LittleVgl.cpp
src/displayapp/LittleVgl.h
src/displayapp/screens/BatteryInfo.cpp
src/displayapp/screens/FirmwareUpdate.cpp
src/displayapp/screens/List.cpp
src/displayapp/screens/Notifications.cpp
src/displayapp/screens/PassKey.cpp
src/displayapp/screens/PassKey.h
src/displayapp/screens/Steps.cpp
src/displayapp/screens/Tile.cpp
src/displayapp/screens/Timer.cpp
src/displayapp/screens/Timer.h
src/displayapp/screens/Twos.cpp
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h
src/displayapp/screens/WatchFacePineTimeStyle.cpp
src/displayapp/screens/WatchFacePineTimeStyle.h
src/displayapp/screens/WatchFaceTerminal.cpp
src/displayapp/screens/WatchFaceTerminal.h
src/displayapp/screens/settings/QuickSettings.cpp

When the screen switches, the full screen needs to be refreshed for the
hardware scrolling to work. This was enforced with backgroundLabels, but
is simpler to do with a rounder function.

Force full screen refresh with a rounder function

---

src/displayapp/lv_pinetime_theme.c
src/displayapp/screens/Metronome.cpp

The scrollbar would go out of bounds if DROPDOWN_PART_LIST had uneven padding.
~~Enable clip_corner feature to stop the selected item from overflowing.~~ Disabled because it is slow.
`style_pad` wasn't doing anything useful, so I removed it.
This is the issue that depends on clip_corner to be fixed. We'll just have to live with it.
Fixes #953

Fix dropdown graphical issues.

---

src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

Instead of having three separate booleans, have just a single state variable.
Now we don't need to worry about checking if it's going to sleep or waking up. If the state is sleeping, it is sleeping and if the state is running, it is running.
This simplified many checks and made the code easier to read.

Simplify systemtask states

---

.github/workflows/format.yml
tests/test-format.sh

Add a GitHub action that clang-formats the changed cpp files, checks them for changes, and if it finds any, create patches for them and upload them as artifacts.
Automating code review will save a lot of time.
An example of this can be seen here https://github.com/Riksu9000/InfiniTime/pull/7
```
Checking src/displayapp/DisplayApp.cpp
Error: Formatting error in src/displayapp/DisplayApp.cpp
Creating patch 0001-Apply-clang-format-to-DisplayApp.cpp.patch
Error: Issues found. You may use the patches provided as artifacts to format the code.
Error: Process completed with exit code 1.
```
[Patches.zip](https://github.com/InfiniTimeOrg/InfiniTime/files/8598505/Patches.zip)

Add clang-format check

---

.github/workflows/lv_sim.yml

This is a very small change to prevent this from being run twice when the pull request is from a branch in this repo, such as in pull #1045. You can see there that this Action was run twice.

Only run lv_sim GH Actions on push to develop and master

---

doc/buildAndProgram.md
src/CMakeLists.txt
src/displayapp/fonts/CMakeLists.txt
src/displayapp/fonts/generate.py

In https://github.com/InfiniTimeOrg/InfiniTime/pull/1097 new font
generation capabilites were added. Generalize the font creation to
make it possible to reuse the `displayapp/fonts/CMakeLists.txt` file
for `InfiniSim` and just add the new cmake file to the project and
link against the new `infinitime_fonts` target.
In the following a list of changes.
Allow non-global installed `lv_font_conv` executable installed with
```sh
npm install lv_font_conv@1.5.2
```
In CMake we search for `lv_font_conv` executable. Add the found
executable to the python script `generate.py`, to remove the need for
`lv_font_conv` to be in the path.
Search for `python3` executable, if CMake version 3.12 is available.
Otherwise use `python` as hard coded executable.
Instead of adding the generated fonts to …

generalize lv-font creation

---

.github/workflows/format.yml
tests/test-format.sh

Don't run the workflow when not necessary.
Ignore libs folder.
Don't allow test-format.sh to be run locally.
Tested here https://github.com/Riksu9000/InfiniTime/pull/7

Format workflow improvements

---

.github/workflows/lv_sim.yml
.github/workflows/main.yml

Remove unnecessary comments in workflows.
Rename uploaded artifacts with the source branch name. The InfiniSim binary doesn't get renamed, only the zip.
Fixes #795

Workflow cleanup and artifact renaming

---

src/components/timer/TimerController.cpp

0 is not valid for xTimerPeriodInTicks, changing it to 1 to pass the assertion

Fix assertion failure in TimerController

---

bootloader/README.md
bootloader/ota-dfu-python/ble_secure_dfu_controller.py
cmake-nRF5x/readme.md
doc/MemoryAnalysis.md
doc/NavigationService.md
doc/PinetimeStubWithNrf52DK.md
doc/ble.md
doc/ble/connection_sequence.puml
doc/branches.md
doc/buildAndProgram.md
nrf52.svd
src/components/ble/DfuService.cpp
src/components/ble/FSService.cpp
src/displayapp/LittleVgl.cpp
src/displayapp/fonts/generate.py
src/displayapp/screens/Screen.h
src/drivers/Bma421_C/bma4.c
src/drivers/Bma421_C/bma4_defs.h
src/sdk_config.h
src/systemtask/SystemTask.cpp
tools/rle_encode.py

Found via `codespell -q 3 -S ./src/libs -L ans,doubleclick,trough`

Fix various typos

---

src/displayapp/screens/ApplicationList.cpp

Moved timer and alarm next to the stopwatch on the first row. Music was moved to where timer was and navigation was moved to where alarm was.
Closes #696

Move basic apps to the top of the app list

---

.github/workflows/format.yml
tests/test-format.sh

Excludes `src/FreeRTOS` as well, and only formats lines that have been changed. Supersedes #1176. Testing is in FintasticMan#3 and FintasticMan#4 again.

Minor changes to clang-format workflow

---

src/displayapp/screens/settings/SettingChimes.cpp
src/displayapp/screens/settings/SettingChimes.h

~~As suggested in https://github.com/InfiniTimeOrg/InfiniTime/pull/1026#issuecomment-1063394505
replace the C-sytle array with a `std::array` and use constexpr variables to access the array to clarify the accessed combobox.~~
ping @JF002 
---
Use a custom `Option` class containing the chimesOption the the corresponding name to render on the display. Create a `std::array` for the possible chimes options and iterate over that to simplify the code (simple loop instead of hard coding all three possibilities)

SettingChimes: replace raw array with std::array

---

src/components/brightness/BrightnessController.cpp
src/components/brightness/BrightnessController.h
src/displayapp/DisplayApp.cpp
src/displayapp/screens/FlashLight.cpp

This feature is not needed and is probably more likely to cause issues. It's better to just use `brightnessController.Set(settingsController.GetBrightness());`

Remove backup brightness feature

---

src/BootloaderVersion.cpp
src/BootloaderVersion.h
src/displayapp/screens/WatchFacePineTimeStyle.cpp

`const` return type doesn't make sense.
~~Weather wasn't handled in LoadApp switch. Added default.~~
Removed unused function.
This doesn't fix warnings generated by nimble and QCBOR

Fix InfiniTime compiler warnings

---

CMakeLists.txt
src/CMakeLists.txt

This PR has been broken out of https://github.com/InfiniTimeOrg/InfiniTime/pull/1050.
- Extended debug configuration
- ~~Use correct linker script in RECOVERY_MCUBOOT~~ merged via #256
- ~~Use iHEX format for mcuboot image creation~~ merged via #256

CMake: Improve debug configuration

---

src/displayapp/fonts/generate.py

In some Linux distributions, binaries are not necessarily stored in `/usr/bin/` (e.g. NixOS).
This PR changes the call to `patch` in `displayapp/fonts/generate.py` to use the `env` tool in order to determine the location of the `patch` tool.

Font generation: Fix patch binary path

---

CMakeLists.txt
doc/buildAndProgram.md
src/CMakeLists.txt
src/drivers/PinMap.h
src/main.cpp

This PR has been broken out of https://github.com/InfiniTimeOrg/InfiniTime/pull/1050.
This enables the compile-time configuration of the LFCLK source, as well as the target hardware board pin configuration.
The `WATCH_COLMI_P8` compilation option has been replaced with `TARGET_DEVICE`, see `doc/buildAndProgram.md`.

Add basic hardware configuration options for P8

---

README.md
doc/InfiniTimeVision.md

Add the initial InfiniTIme Vision document that has been written in collaboration with the core developers. This document will help steer efforts towards a common goal by having the goals of the project written down and visible to everyone.
Since the last draft I added some context to the top of the document and using standard protocols as a core principle.

Add InfiniTime Vision document

---

.github/workflows/lv_sim.yml
.github/workflows/main.yml

No reason to run these checks in that case.

Don't build the firmware when only docs were modified

---

src/displayapp/screens/Twos.cpp
src/displayapp/screens/Twos.h

Made the interface slightly larger.
Removed magic row and col counts. The size can be increased to 5x5 for example just by incrementing a value.
Fixed many warnings.
Reduced for loop count. Each either save a few bytes or no change.
Reduced library dependency.
In `updateGridDisplay()` only a for loop was removed and the indentation changed. The diff looks more complicated.

Twos code cleanup

---

src/CMakeLists.txt
src/libs/mynewt-nimble/nimble/drivers/nrf52/src/ble_phy.c
src/libs/mynewt-nimble/porting/nimble/include/logcfg/logcfg.h
src/libs/mynewt-nimble/porting/nimble/include/modlog/modlog.h
src/libs/mynewt-nimble/porting/npl/freertos/include/nimble/nimble_npl_os.h
src/libs/mynewt-nimble/porting/npl/freertos/src/npl_os_freertos.c

This PR has been broken out of https://github.com/InfiniTimeOrg/InfiniTime/pull/1050 .
- Reduce BLE power usage by only powering up radio peripherals and the high frequency clock when needed (`BLE_LL_RFMGMT_ENABLE_TIME` parameter)
- Use NRF SDK to access high frequency clock, in order to not interfere with potential LFRC calibration.

Nimble: Reduce power usage, add compatibility to LFCLK calibration

---

src/CMakeLists.txt
src/displayapp/screens/SystemInfo.cpp

This PR has been broken out of https://github.com/InfiniTimeOrg/InfiniTime/pull/1050, and depends on / includes https://github.com/InfiniTimeOrg/InfiniTime/pull/1128 .
This PR uses the last line on the second screen in the system information to display the target build variant, i.e. which device the firmware was compiled for. This is very useful to know which updates to download, once you have forgotten which variant your device is.

SystemInfo: Display target build variant

---

.github/workflows/docker.yml

This PR adds a GitHub Actions workflow that builds the Docker image and pushes it to Docker Hub whenever anything in the `docker/` directory is changed. I've tested it [here](https://github.com/FintasticMan/InfiniTime/actions/runs/2505633550), and the images have been pushed [here](https://hub.docker.com/r/fintasticman/infinitime/tags).
Any pull requests should just build the image, but not upload it to Docker Hub. It should also be possible to publish to different tags than just latest by using docker/metadata-action, I just haven't gotten around to that yet.
Before merging, the secret `DOCKER_HUB_ACCESS_TOKEN` will be needed to be added to this repository.

Create GH Actions workflow to build Docker image

---

.github/workflows/docker.yml

@JF002 This pull request fixes the issue mentioned [here](https://github.com/InfiniTimeOrg/InfiniTime/pull/1184#issuecomment-1179127636) about that the username used for logging in to Docker Hub is different than the one that actually has the images. This works around it by having 2 secrets: `DOCKER_HUB_LOGIN_USERNAME`, which should be set to (in this case) `jf002`, and `DOCKER_HUB_IMAGE_USERNAME`, which should be set to `infinitime`.
I don't have an organisation on Docker Hub to test it out on, but I have tested it on my personal repository, with both secrets set to `fintasticman`, and it works fine.

Docker workflow use separate username for login

---

src/displayapp/DisplayApp.cpp

Previously it was restored only when specifically returning to the previous app.
Fixes #1201

Always restore brightness on app switch

---

src/displayapp/screens/FlashLight.cpp

Backlight brightness is unlimited while the flashlight is on.
While it is off, the brightness is limited to the global backlight level.
Small code optimizations.
Fixes #1210

Limit backlight brightness when flashlight is off

---

src/displayapp/screens/Timer.h
src/displayapp/screens/settings/SettingSetTime.cpp
src/displayapp/screens/settings/SettingSetTime.h
src/displayapp/widgets/Counter.cpp
src/displayapp/widgets/Counter.h

The Counter widget was extended with custom font support, twelve hour mode and value changed callback.
SettingSetTime was reworked to use Counter, along with other small optimizations.

Use Counter widget in SettingSetTime

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Timer.cpp
src/displayapp/screens/Timer.h
src/libs/lv_conf.h

To not clutter the interface, I added long pressing to reset the timer with visual feedback.

Reset timer by long pressing on the button

---

src/CMakeLists.txt
src/displayapp/DisplayApp.cpp
src/displayapp/screens/ApplicationList.cpp
src/displayapp/screens/ApplicationList.h
src/displayapp/screens/Tile.cpp
src/displayapp/screens/Tile.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h
src/displayapp/screens/settings/QuickSettings.cpp
src/displayapp/screens/settings/QuickSettings.h
src/displayapp/widgets/StatusIcons.cpp
src/displayapp/widgets/StatusIcons.h

Add a widget that handles the status icons and proper alignment without inconsistent gaps. Fixes issue with #1137.

Add status icons widget

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/Alarm.cpp
src/displayapp/screens/Alarm.h

Use the Counter widget in alarm. The Info feature was retained by making it a transparent button that stretches above the time, so you can see the info by tapping the time.

Use Counter widget in Alarm

---

src/displayapp/screens/StopWatch.cpp
src/displayapp/screens/StopWatch.h

Overriding the earlier laps doesn't seem like a good idea when the intention is to make all of the saved laps accessible. Previous laps will be made accessible in another PR.
This is a part of #612 rewritten.

Simplified stopwatch lap buffer

---

src/displayapp/lv_pinetime_theme.c
src/displayapp/screens/settings/SettingDisplay.cpp
src/displayapp/screens/settings/SettingDisplay.h
src/displayapp/screens/settings/SettingTimeFormat.h
src/displayapp/screens/settings/SettingWakeUp.cpp
src/displayapp/screens/settings/SettingWatchFace.h

Added timeout options in a way which requires fewer clicks than #1222 as suggested by @mashuptwice. I want to make these larger, but I thought I'd do that in another PR.
Also improved the checkbox inner padding so the extra whitespace can be removed without visible changes.

More timeout options and improved checkbox alignment

---

src/displayapp/screens/Notifications.cpp

Improves visibility. Also reduced code duplication slightly. Fixes #972.

Notification swap text colors

---

src/displayapp/screens/settings/SettingSetDate.cpp
src/displayapp/screens/settings/SettingSetDate.h
src/displayapp/widgets/Counter.cpp
src/displayapp/widgets/Counter.h

Counter was expanded with month mode, variable digit count and a minimum width.
The counter will always show at least two digits with leading zeroes if necessary. This doesn't impact anything currently, but it's worth considering and I'll see if I can find a neat solution to this.

Use Counter widget in SetDate

---

src/CMakeLists.txt
src/drivers/St7789.cpp

This PR has been broken out of https://github.com/InfiniTimeOrg/InfiniTime/pull/1050, and depends on / includes https://github.com/InfiniTimeOrg/InfiniTime/pull/1128 .
A new P8b hardware variant requires the display to be mirrored, and the colors to be inverted. Patch provided by @izzeho .
Related: https://github.com/StarGate01/p8b-infinitime/issues/3

P8: Mirror display for P8b variant

---

src/displayapp/widgets/Counter.cpp
src/displayapp/widgets/Counter.h

Previously the minimum number of digits was fixed at two, padded with leading zeros if necessary. Now it will be determined from the max value. 
Current:
`00, 01, 02 ... 99, 100, 101 ... 999, 1000 1001`
With this change:
`0000, 0001, 0002 ... 0099, 0100, 0101 ... 0999, 1000, 1001`
This issue doesn't happen with the current uses of the Counter.

Counter: Determine the number of digits from the max value.

---

src/components/settings/Settings.h
src/displayapp/fonts/fonts.json
src/displayapp/screens/Symbols.h
src/displayapp/screens/settings/QuickSettings.cpp
src/displayapp/screens/settings/QuickSettings.h
src/systemtask/SystemTask.cpp

A sleep mode is needed so the watch can be worn during the night without causing the menus to activate.
Sleep mode disables notifications, touch wakeup, motion wakeup and chimes.
Fixes #689

Add sleep mode

---

src/displayapp/screens/Twos.cpp
src/displayapp/screens/Twos.h

Move cell styles to an array. Saves some memory.

Reduce duplication in Twos

---

src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/widgets/StatusIcons.cpp

Making the icons white Improves the visibility, but also makes them more subdued instead of attention grabbing. I was planning on making this change regardless of #1263.
Relates to #958. One of the necessary changes for #1263.

Improve status icon visibility

---

src/displayapp/screens/Error.cpp
src/displayapp/screens/Metronome.cpp
src/displayapp/screens/Metronome.h
src/displayapp/screens/WatchFacePineTimeStyle.cpp
src/displayapp/screens/settings/SettingSetDate.cpp
src/displayapp/screens/settings/SettingSetDate.h
src/displayapp/screens/settings/SettingSetTime.cpp
src/displayapp/screens/settings/SettingSetTime.h
src/displayapp/screens/settings/SettingSteps.cpp
src/libs/lv_conf.h

value_str is a way to add text on a button without a separate label.
This saves having an extra label object, but I believe it's removed in LVGL8.
Disabling this saves some memory, but using value_str everywhere would probably also save some memory. value_str can make slightly cleaner code, but isn't good for future proofing. Thoughts?

Disable LVGL value_str

---

src/components/alarm/AlarmController.cpp
src/components/alarm/AlarmController.h

A small trivial change for correctness. No functional change.
The function `SecondsToAlarm()` doesn't change anything in the `AlarmController` object. Mark the function `const` to show this property.

AlarmController: add const to SecondsToAlarm() function

---

src/displayapp/screens/Clock.cpp
src/displayapp/screens/Clock.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h
src/displayapp/screens/WatchFacePineTimeStyle.cpp
src/displayapp/screens/WatchFacePineTimeStyle.h
src/displayapp/screens/WatchFaceTerminal.cpp
src/displayapp/screens/WatchFaceTerminal.h

The title says it all. There is a typo in Clock that made its way into the other watch faces (but not WatchFaceAnalog!).

fix typo: notificatioManager -> notificationManager

---

src/displayapp/screens/WatchFacePineTimeStyle.cpp
src/displayapp/screens/WatchFacePineTimeStyle.h

After receiving a PineTime for Christmas, I started trying to code a bit for it. The first thing I noticed was that the very nice PineTimeStyle watch face does not show the seconds, so I changed that. The design is adapted from the [original Pebble TimeStyle](https://apps.rebble.io/en_US/application/55a5c024f4510f794c000071), where the seconds are also displayed in the bottom right corner. I therefore had to move the step counter up and to avoid coming to near to the calendar, I also changed the step counter to be a half circle instead of a full circle.
I am using the very same changes (but applied to master) since more than a week now on my PineTime and it works perfectly fine, but since I only have a sealed version, I didn't dare to flash the develop branch with the changes. However, I …

PTS: add seconds display

---

src/displayapp/screens/WatchFacePineTimeStyle.cpp

Building current develop results in the new PTS 'Steps style' button having a blank/missing label. I think this is due to a conflict with #1273 and is fixed by this change.
edit: this problem may also affect Infineat watchface buttons

Fix PTS steps style button label

---

doc/InfiniTimeVision.md
doc/MemoryAnalysis.md
doc/gettingStarted/gettingStarted-1.0.md
doc/gettingStarted/updating-software.md
src/components/ble/weather/WeatherData.h
src/displayapp/screens/WatchFacePineTimeStyle.cpp

Exact opposite of #1303 .
Before:
```bash
╰─$ grep -r "Watchface\|watchface"                                                                                                                                                                           130 ↵
doc/MemoryAnalysis.md:Using this technique, I was able to trace all malloc calls at boot (boot -> digital watchface):
doc/InfiniTimeVision.md:- Personalization is achieved through custom watchfaces.
doc/InfiniTimeVision.md:- Capability to sideload apps and watchfaces
doc/gettingStarted/updating-software.md:You can check the InfiniTime version by first swiping right on the watchface to open quick settings, tapping the cogwheel to open settings, swipe up until you find an entry named "About" and tap on it. …
```

Edit all occurences of "watchface" to "watch face"

---

.github/workflows/format.yml
src/displayapp/DisplayApp.cpp
src/systemtask/SystemTask.cpp
tests/test-tidy.sh

Added a new check that displays clang-tidy warnings for changed files. This check isn't blocking, because a lot of warnings exist in the codebase and the rules may need to be tweaked, but can be used for reference. I've added some fixes that trigger the check for demonstration.
I think we should work to fix these warnings or disable them if they're not important. These warnings aren't necessarily about fixing bad code, but rather consistent practices, so silencing or switching some of them isn't an issue. Let me know what you think.

Clang tidy check

---

src/components/settings/Settings.h
src/displayapp/screens/CheckboxList.cpp
src/displayapp/screens/CheckboxList.h
src/displayapp/screens/settings/SettingWatchFace.cpp

I'm not completely satisfied of the design of CheckBoxList. It currently depends on SettingsController and receives pointers to function to get and set the setting.
CheckBoxList is a UI component that we should be able to use anywhere. But the current implementation limit the usage of this class to settings that are handled by the `Settings` controller.
I tried to refactor this class : it now receives the `originalValue` (which is used to select the corresponding checkbox) and a `std::function` that is called when the value changes. This allows to completely de-couple `CheckBoxList` from `Settings`.
Now, I know that lambda with capture and std::function can have a big overhead (heap allocation, binary size and execution time). I couldn't find any in this specific case, but I wouldn't mind …

Refactoring of CheckBoxList : remove dependency to SettingController

---

.github/workflows/main.yml

https://github.com/InfiniTimeOrg/InfiniSim/pull/70 introduces the `BUILD_RESOURCES` cmake configuration option enabled per default.
Disabling it on InfiniTime side for the CI-pipelines from InfiniTime as the `BUILD_RESOURCES` functionality is already tested in the firmware build itself

CI: disable BUILD_RESOURCES for InfiniSim as already done in firmware

---

src/components/ble/CurrentTimeClient.cpp
src/components/ble/CurrentTimeClient.h
src/components/ble/CurrentTimeService.cpp
src/components/ble/CurrentTimeService.h
src/components/datetime/DateTimeController.cpp
src/components/datetime/DateTimeController.h

I implemented a small TOTP Screen for my watch and thus needed access to UTC. When checking on how to get this information from my phone to the watch, I found and implemented the Local Time Characteristic of the Current Time Service BLE specification. This allows the companion app to transmit information about the current timezone as well as dst in effect.
~~When checking for related PRs and Issues I found #365 and thought that I'd implement parts of it allowing to show UTC on the watch.~~
* implemented the Local Time Characteristic in `CurrentTimeService`
* added a check to both Local Time and Current Time to ignore too short data
* corrected the definition of the `CtsCurrentTimeData` struct in `CurrentTimeClient` as well as `CurrentTimeService` to match the specification
* added fields …

Extend CTS Server

---

src/displayapp/screens/WatchFaceTerminal.cpp

Based on @NeroBurner's comment in #1339 I factored this quick fix out.
There is a leftover(?) line in TerminalWatchFace that does not seem to serve a purpose.

Remove not needed SetClockFace from terminal watch face constructor

---

src/components/ble/weather/WeatherService.cpp

This PR fixes an issue with the WeatherService GetToday[Min:Max]Temp functions which miscalculated the timestamp of the current day end. I also made a change which makes it find all events between day start & day end (instead of only non-expired events before day end) which as far as I can see is reasonable for this function (find highest and lowest values for the current 24h period). Testing will reveal how different weather data providers set expiry time and what that means for us...

WeatherService daily min/max temperature fixes

---

src/components/ble/CurrentTimeService.h
src/components/datetime/DateTimeController.cpp
src/components/datetime/DateTimeController.h

This is a hotfix for  #1161.
I am afraid I got misled by the BLE spec, which specified the timezone fields as `uint8`. But, to be able to express negative timezones, they need to be signed.

BLE CTS: fixed signedness of timezone

---

doc/buildWithDocker.md

AMD64 and x86_64 are the same architecture - ARM64 should be specified instead

typo in the description

---

src/displayapp/screens/Weather.cpp
src/displayapp/screens/Weather.h
src/displayapp/widgets/Counter.cpp

* Fixed #1035 by removing unused member (can be added back when needed)
* Reordered member initialization in `Counter.cpp` to remove compiler warning

Fix #1035 and unreported compiler warning.

---

.devcontainer/build.sh
docker/build.sh

If I see it correctly, I can not verify this fix, as the PR build does not use the build.sh from this PR. But from looking at it, this should fix #1292

Fixing build-firmware not returning error at the correct step

---

src/displayapp/screens/WatchFacePineTimeStyle.h

Small fix to be consistent: use "" for our includes and <> for system includes or packages by others.

PineTimeStyle: use "" for our includes

---

src/displayapp/screens/Notifications.cpp
src/displayapp/screens/Notifications.h

Make it possible to dismiss new notifications in the preview screen with SwipeRight, as suggested in #1232.

Make it possible to dismiss new notifications in the preview screen

---

.clang-format
.github/workflows/format.yml
src/components/ble/BatteryInformationService.cpp
src/components/ble/MotionService.cpp
src/components/datetime/DateTimeController.cpp
src/components/fs/FS.cpp
src/components/motion/MotionController.cpp
src/displayapp/DisplayApp.cpp
src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
src/displayapp/screens/settings/SettingSetTime.cpp
src/displayapp/widgets/Counter.cpp
src/drivers/Bma421.cpp
src/drivers/DebugPins.cpp
src/drivers/Hrs3300.cpp
src/recoveryLoader.cpp
tests/test-format.sh
tests/test-tidy.sh

Now that the GH Actions VMs have updated to Ubuntu 22.04, clang can be updated to 14 over 12. I've looked through all the clang-format options that have been added in 13 and 14, and added the ones I believe fit our coding style. These options are: `EmptyLineAfterAccessModifier: Never`, `IndentAccessModifiers: false`, `PackConstructorInitializers: Default`, `ReferenceAlignment: Pointer` and `SeparateDefinitionBlocks: Always`. All of these except the last one don't actually change the formatting at all, just prevent any incorrect formatting in the future. The last one adds some new lines between definition blocks in some cases.
This change fixes a compiler error in the clang-tidy check, about the `-fstack-usage` flag.

Update clang-{format,tidy} to 14

---

.github/workflows/docker.yml
.github/workflows/main.yml

ubuntu-latest vm has been updated from 20.04 to 22.04. To avoid sudden issues, use 22.04 explicitly.
CMake doesn't need to be updated on 22.04.
actions/checkout@v2 uses deprecated Node.js 12. Update to v3 which uses 16
Fixes warnings in builds. https://github.com/InfiniTimeOrg/InfiniTime/actions/runs/3811961913

Update workflow dependencies

---

.github/ISSUE_TEMPLATE/config.yml

This PR goes together with #1267 where we removed the feature request template. 
In this PR, we suggest the users to file their feature requests in the Discussions board.

Add a link to the "Ideas" (feature requests) Discussions board in the Github contact links

---

README.md
doc/maintainer-guide.md

This document clarifies how the maintainers should manage the project.
We should write about using the milestones as well, but I want to discuss that first. I'll open an issue about that. If that doesn't get resolved in time, it can be another PR. EDIT: Here's the issue #1515
I've added new instructions on handling stale PRs. Three months is quite conservative, as it concerns any activity, and can be reduced. Let me know what you think.

Add maintainer's guide

---

doc/code/Apps.md

This fixes Apps creation documentation old and no longer correct `DisplayApp::LoadApp`, it was at some point replaced/renamed to `DisplayApp::LoadScreen`.
As a beginner myself it was confusing first time setting up, correct information here would be more inviting to new people :)

Fix Apps documentation DisplayApp method name

---

src/components/battery/BatteryController.cpp

This pull request modifies the values of the discharge curve to slightly more accurately estimate the battery discharge. To calculate these values, I have run different tests on my 3 PineTimes, and then used some code to find the best fit. I can provide the raw data from the watches as well as the code I used on request.
In this last graph, the blue line is the original linear algorithm, the red line is with AlexXZero's values, and the yellow line is with my values.

Improve discharge curve values

---

.github/workflows/main.yml

The `github.event.pull_request.base.sha` in the workflow doesn't get updated when there are new commits in the base branch. Instead always checkout the branch to check the sha manually and cache only the build.
The ownership fix seems to still be necessary

build-size-workflow: Fix when base gets updated

---

src/displayapp/screens/settings/SettingBluetooth.cpp
src/displayapp/screens/settings/SettingBluetooth.h
src/displayapp/screens/settings/SettingChimes.cpp
src/displayapp/screens/settings/SettingChimes.h

Only timeout and wakeup screens left, which will require changes in CheckboxList.

Use checkboxlist in Bluetooth and Chimes settings

---

.github/workflows/main.yml
.github/workflows/pr-comment.yml

This works by uploading the data from the main workflow with low permissions as an artifact, then downloading the data in a workflow with higher permissions to post the comment.
Third party actions are fixed at a commit, in case they get compromised.
Also set the build-firmware VM to ubuntu-22.04, which was missed when updating workflow deps earlier.
This will not run on this PR, because pull_request_target runs in the context of the base branch, but this file doesn't yet exist in develop.

Comment build size on all PRs

---

.github/workflows/main.yml
.github/workflows/pr-comment.yml

The previous version failed, because it looked for the check from the branch in the fork, but looked for it in the main repo. Now uses the sha to get the commit on which checks were run.
Previous description
This works by uploading the data from the main workflow with low permissions as an artifact, then downloading the data in a workflow with higher permissions to post the comment.
Third party actions are fixed at a commit, in case they get compromised.
Also set the build-firmware VM to ubuntu-22.04, which was missed when updating workflow deps earlier.

workflow: Updated workflow comment for all

---

.github/workflows/pr-comment.yml

The workflow checks that the buildsize comparison succeeds. The download artifact step also checks that all of the main workflow succeeds. This isn't necessary, and causes the comment not to be created when the simulator build fails. This change disabled the success conclusion requirement.

workflow: Buildsize comment when simulator fails

---

doc/contribute.md

Denser instructions for absolute beginners. Links to GitHub docs.
Add PR checklist and commit conventions sections based on the maintainer's guide.
Add commit format section. Inspired by https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages
Closes #1516

Update contributing doc

---

src/displayapp/screens/settings/SettingSteps.cpp

Closes #1427
Long pressing will change the value by 1000, whereas clicks will change
it by 500. This allows setting more precise values, while also making it
easier to set any value.
Ignore the fact that the animation is way too fast.

Update setsteps UI

---

.clang-format
src/StaticStack.h
src/components/utility/LinearApproximation.h
src/displayapp/screens/Screen.h
src/displayapp/screens/ScreenList.h

I find this format easier to read, because the definitions are at the expected indentation, making it easier to find what I'm looking for.

clang-format: Always break template declarations

---

doc/buildAndProgram.md

This is a small change to prevent the use of too many threads locking up the system. This is an issue I've seen in the chat room a few times, especially when people are running in a virtual machine with a small amount of RAM allocated.
All it does is only let `make` use as many jobs as there are threads.

docs: Limit number of jobs used for compilation

---

src/displayapp/DisplayApp.cpp
src/displayapp/LittleVgl.cpp
src/displayapp/LittleVgl.h
src/main.cpp
src/systemtask/SystemTask.cpp
src/touchhandler/TouchHandler.cpp
src/touchhandler/TouchHandler.h

Moved LVGL handling out of TouchHandler, so it just processes Cst816S data.
Removed Cst816S dependency from TouchHandler. Cst816S::TouchInfo is simply passed to the processing function.
Outside the scope of this PR, but since TouchHandler is just processing Cst816S data to an InfiniTime friendly format, this code could in the future be moved inside the driver itself, so different touch drivers would have their own processing functions.

Touchhandler rework

---

src/components/ble/CurrentTimeClient.cpp
src/components/ble/CurrentTimeService.cpp
src/components/ble/NimbleController.cpp
src/components/datetime/DateTimeController.cpp
src/components/datetime/DateTimeController.h
src/displayapp/screens/settings/SettingSetDate.cpp
src/displayapp/screens/settings/SettingSetTime.cpp
src/main.cpp

The systick doesn't need to be updated when setting time.
Also removed unused nrf_rtc.h includes.
I guess this change will make it so depending on the previous systick value, the time can shift an amount less than one second. Is this a problem?

DateTimeController: Remove SetTime tick parameter

---

src/components/datetime/DateTimeController.h

`tm_yday` is an int and is a number between 0 and 365.

DateTimeController: Fix integer overflow on day of year

---

src/displayapp/screens/WatchFaceInfineat.cpp
src/displayapp/screens/WatchFaceInfineat.h

lv_color_hex can't be evaluated at compile time, but LV_COLOR_MAKE can.
I feel like there must be a better approach that I'm missing. Let me know if you have ideas.

infineat: Create colors at compile time.

---

src/components/fs/FS.cpp
src/components/fs/FS.h
src/displayapp/DisplayApp.cpp
src/displayapp/LittleVgl.cpp
src/displayapp/LittleVgl.h

Previously, the LVGL driver for the filesystem was initialized in the class FS. However, since 6f942e2, the order of the initializations was incorrect  : the driver was initialized (FS::LVGLFileSystemInit()) before LVGL (LittleVgl.Init()), which means that the driver registration was probably dropped when LVGL was initialized.
The LVGL driver is now initialized in LittleVgl.Init(), which seems to make much more sense, since all LVGL drivers are initialized there. This way, we ensure that the initialization of the drivers is consistent.

LVGL / FS : Initialize the LVGL FS driver in LittleVgl (instead of FS).

---

README.md

I don't think this badge has shown the actual status of the current workflows for a long time. The real status can easily be seen by clicking on the checkmark or cross icon on the front page. It's also supposed to show the status of the master branch, not develop (default).

README: Remove status badge

---

src/components/battery/BatteryController.cpp
src/components/battery/BatteryController.h
src/displayapp/InfiniTimeTheme.h
src/displayapp/screens/BatteryIcon.cpp
src/displayapp/screens/BatteryIcon.h
src/displayapp/screens/BatteryInfo.cpp
src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
src/displayapp/screens/WatchFacePineTimeStyle.cpp
src/displayapp/widgets/StatusIcons.cpp
src/systemtask/Messages.h
src/systemtask/SystemTask.cpp

This reverts PR https://github.com/InfiniTimeOrg/InfiniTime/pull/1352
There's no need to break the focus of the user to alert them that the battery will be empty in 24h, when they can see that the next time they check the watch. I've made the battery icon turn orange at 15, and red at 5, for a stronger warning to charge the watch.

Revert low battery alert. Add low battery indicator.

---

src/displayapp/screens/WatchFacePineTimeStyle.cpp

Fixes #1467 "Double tapping PineTimeStyle steps style button sends watch to sleep"
Double tap is disabled on the color settings screen by checking if the Rnd button is visible, but this didn't work for the options screen as the Rnd button isn't visible. I've changed it to check if the Close button is visible instead, which is used on both settings screens, and resolves the bug. I also changed the button used to disable the long press behaviour which was an as-yet-undiscovered bug which would have allowed the long press action to be used when the options screen was visible.

Fix double tap behaviour on PineTimeStyle settings screen

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h
src/displayapp/Messages.h
src/displayapp/screens/settings/SettingDisplay.cpp
src/systemtask/Messages.h
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

Replace custom FreeRTOS inactivity timers with LVGL inactivity timers.
There may be some more optimizations possible, for example the restore brightness message can probably be replaced with `lv_disp_trig_activity(nullptr);`
~~- [ ] Fix an issue where setting the timer to the exact timeout setting causes the watch to go to sleep at the time the timer expires.~~ Looks like this isn't a new issue and shouldn't be blocking.

inactivity: Use LVGL inactivity timers

---

.github/workflows/pr-comment.yml

People are confused by the failing pr-comment check. Instead of failing, write a different comment describing the issue.
Tested in https://github.com/Riksu9000/InfiniTime/pull/22 by cancelling the build. See the history of the comment.

pr-comment: Comment instructions instead of failing

---

src/displayapp/screens/StopWatch.cpp
src/displayapp/screens/StopWatch.h

Addresses https://github.com/InfiniTimeOrg/InfiniTime/issues/394
It adds hours without changing any of the existing formatting, but by re-using it as needed.
Once the timer is > 1 hour, the main display becomes Hours:Minutes, and the part beneath becomes Seconds:Milliseconds. Lap timer will display "Hours:Minutes:Seconds.Milliseconds" when a lengthy timer is recorded.

stopwatch: Add hours tracking

---

src/displayapp/fonts/generate.py

The generate script should only output anything if there are errors.

fonts: Make patching silent

---

src/components/motion/MotionController.h
src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
src/displayapp/screens/WatchFaceCasioStyleG7710.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h
src/displayapp/screens/WatchFaceInfineat.cpp
src/displayapp/screens/WatchFaceInfineat.h
src/displayapp/screens/WatchFacePineTimeStyle.cpp
src/displayapp/screens/WatchFacePineTimeStyle.h
src/displayapp/screens/WatchFaceTerminal.cpp
src/displayapp/screens/WatchFaceTerminal.h
src/systemtask/SystemTask.cpp

The application shouldn't be concerned with the sensor being initialized, because the values just wouldn't be updated. DisplayApp also isn't started before the sensor is initialized.
Extracted from #1700

Watchfaces: motionsensor is ok

---

src/displayapp/screens/SystemInfo.cpp
src/drivers/Watchdog.cpp
src/drivers/Watchdog.h
src/systemtask/SystemTask.cpp

Refactor and document the Watchdog driver to make it more readable.
Fix the configuration of the behaviours configuration that was not properly implemented (but it didn't cause any side effect since the correct value was eventually set in NRF_WDT->CONFIG).
Fix the wrong interpretation of the reset reasons caused by implicit conversions of int to bool.
Watchdog is now probably one of the most documented class of the project. What do you think of this format? It's quite helpful in IDEs that support Doxygen like CLion:
This PR is an alternative solution to https://github.com/InfiniTimeOrg/InfiniTime/pull/1705.

Refactor, document and fix the Watchdog driver

---

src/drivers/Hrs3300.cpp

Put the HRS3300 to sleep mode when InfiniTime is going to sleep. This change reduces the power consumption by 130µA when the heart rate sensor is disabled.

Power optimization - Enable HRS3300 (heart rate sensor) sleep mode.

---

src/main.cpp

The DC/DC regulator reduce the power consumption of the MCU compared to the default LDO regulator. The DC/DC regulator needs additional HW that is mounted on the PineTime.
This change reduces the power usage by 380µA during fast advertising, by 200µA during slow advertising and by 186µA when BLE is disabled.

Power optimization - enable the DC/DC regulator.

---

src/drivers/PinMap.h
src/drivers/Spi.cpp
src/drivers/SpiMaster.cpp
src/drivers/SpiNorFlash.cpp
src/drivers/St7789.cpp
src/drivers/St7789.h
src/main.cpp
src/recoveryLoader.cpp

Ensure that all pins are set to their default configuration during sleep mode. Disable the workaround for FTPAN58 (SPI freezes when transfering a single byte) at the end of the transfer. This disables the resources needed for the workaround. Those changes reduce the power usage by 430-490µA.

Power optimization - Improve SPI sleep mode

---

tools/mcuboot/imgtool/boot_record.py

The mcuboot imgtool uses the python module `cbor`.
An equivalent and updated package `cbor2` requires Python 3.7 or newer.
The arch packages provide a package `python-cbor2`, but no package for `cbor`.
This patch makes it possible to use the system package by adding support for the `cbor2` package additionally to the `cbor` package.

Allow mcuboot tool to use cbor2 additional to cbor

---

src/components/ble/NotificationManager.h

This pull request is extracted from #1482 and changes the order for the notification struct fields to allow the creation of notifications using a string literal like this:
```cpp
NotificationManager::Notifiation notification {
"String literal with notification text",
42,
NotificationManager::Categories::SimpleAlert
};
```

Reorder notification struct fields

---

doc/buildWithDocker.md

As a novice I've struggled quite a bit with Docker build and with issues like https://github.com/InfiniTimeOrg/InfiniTime/issues/1807 it looks like a good idea to include repository initialization in Docker build documentation as well.

[docs] Include repository initialization in docker build doc

---

src/CMakeLists.txt
src/components/motion/MotionController.cpp
src/components/motion/MotionController.h
src/systemtask/SystemTask.cpp
src/utility/CircularBuffer.h
src/utility/Math.cpp
src/utility/Math.h

Depends on #1696 and #1726.
Fixes #548.
With this implementation, your hand needs to be raised at a certain speed to register.
The values for the speed and threshold are values that feel about right to me, but I'm up for changing them.

Improve Raise to Wake algorithm

---

src/components/motion/MotionController.cpp
src/components/motion/MotionController.h
src/components/settings/Settings.h
src/displayapp/screens/settings/SettingWakeUp.cpp
src/displayapp/screens/settings/SettingWakeUp.h
src/systemtask/SystemTask.cpp

This feature makes the device go to sleep if you lower your wrist.
Closes #713.

Implement Lower to Sleep functionality

---

src/components/ble/weather/WeatherService.cpp

It was potentially possible that an event with a timestamp in the future could be returned as a current event.

weather: Fix GetCurrent* functions returning future events

---

.devcontainer/Dockerfile
.github/workflows/main.yml
doc/buildAndProgram.md
docker/Dockerfile
src/resources/CMakeLists.txt
src/resources/generate-img.py
src/resources/lv_img_conv.py

Create a minimal python port of the node.js module `lv_img_conv`. Only
the currently in use color formats `CF_INDEXED_1_BIT` and
`CF_TRUE_COLOR_ALPHA` are implemented.
Output only as binary with format `ARGB8565_RBSWAP` (and `ARGB8888` for debugging).
This is enough to create the `resources-1.13.0.zip`.
In the simulator the pinecone in Casio is visible, and the navigation symbol is visible as well in the simulator when the resource zip is loaded
The new `lv_img_conv.py` script needs `python3-pil` python module as runtime dependency.
The runtime dependency is added to the docker container image.

lv_img_conv_py: minimal python port of node module

---

docker/Dockerfile

This resolves a deprecation warning with the `nodejs` package (#1846).

Update NPM installation for containers

---

src/displayapp/DisplayApp.cpp

When a notification is received, SystemTask sends messages to DisplayApp, which loads the Notifications apps that sends a few messages to SystemApp. When notification are received too quickly, DisplayApp and SystemTask cannot process those messages fast enough (probably because of the time it takes to refresh the display) and the message queues fill up. When they are full, the current implementation just waits until there's room available to store the event. In this case, since both tasks exchange messages, they end up in a deadlock.
This fix consists in setting the timeout value to 0 (non-blocking mode) for the NewNotification messages on the DisplayApp side. This will prevent the SystemTask from being blocked (which would result in the watchdog reseting the watch). A more generic …

Fix deadlock when a lot of notifications are received in a very short time span

---

src/displayapp/Apps.h

The build-time selection PR updated the order, this restores what it was before. I feel this has more frequently used apps on the first page, and less frequently used ones on the second. If someone has a better order, please tell me.

apps: Restore app list order

---

src/displayapp/screens/ApplicationList.h

Was testing an extra app (so 12 in total) and noticed the extra screen added
Also removed the old comment
There might be a nicer C++ way to do this than this macro I spotted lying around, but I can't find one

Fix calculation of number of app screens

---

src/displayapp/screens/ApplicationList.h

Fix 'nScreens' calculation in ApplicationList so that we can build the project with zero user app selected.

Allow zero app to be selected at build time

---

README.md

The InfiniLink app is now maintained, and doesn't need the 'Looking for Maintainer' label anymore.

Remove 'Looking for Maintainer' in README.md

---

src/displayapp/screens/WatchFacePineTimeStyle.cpp

When navigating into the PineTimeStyle watch face and weather display is on, the weather icon is set as "cloudSunRain" until it is updated to the correct icon in the Refresh function. (This behavior is most prominent when navigating from the Quick Settings.) The "temperature" variable is not set until the Refresh function is called, so it displays "Text" until it is updated in the function. This PR aims to fix that by setting the default value of temperature to "--" and the weather icon to "ban".

PineTimeStyle: fix brief display of weather dummy data

---

src/displayapp/screens/settings/SettingWeatherFormat.cpp

The icon used in the WeatherFormatSetting.cpp file was incorrect. This PR changes the icon to the cloudSunRain symbol.
(This is a second PR because I accidentally committed an unrelated change to the branch being used for the first PR. Sorry about that!)

Update incorrect icon in weather settings

---

doc/SimpleWeatherService.md
src/components/ble/SimpleWeatherService.cpp

In the documentation, specify that the timestamp is expressed in seconds from epoch (instead of nanoseconds). SimpleWeatherService now uses "localtime" (GetCurrentDateTime()) instead of UTC time.

Simple Weather Service : Fix timestamp

---

hooks/pre-commit

This updates the pre-commit hook to use git-clang-format.

Update pre-commit hook

---

src/displayapp/screens/WatchFacePineTimeStyle.cpp

Since returning a valid weather is always considered an updated value, if the current weather is empty, the face will attempt to display the temperature and icon as empty values, rather than clearing the labels.

WatchFacePineTimeStyle: Fix conditional in weather display

---

src/CMakeLists.txt
src/displayapp/screens/WeatherSymbols.cpp
src/displayapp/screens/WeatherSymbols.h

When I was adding the new `SimpleWeatherService` to my Star Trek Watchface, the linker got confused about multiple implementations of `Pinetime::Applications::Screens::Symbols::GetSymbol`.
Including `WeatherSymbols.h` in two different files declared and implemented it two times.
This fixes that problem, by splitting the declaration and implementation of said function.

Split declaration and implementation of GetSymbol

---

src/resources/lv_img_conv.py

Support other image modes like `P`, which uses 8 bits per pixel and a color palette to save space.
Luckily the Pillow module can do the mode conversion for us.
Fixes: https://github.com/InfiniTimeOrg/InfiniTime/issues/1985

lv_img_conv: support other modes like 'P'

---

src/components/ble/MotionService.cpp
src/components/ble/MotionService.h
src/components/motion/MotionController.h
src/systemtask/SystemTask.cpp

This PR fixes the motion service not being updated when the device is sleeping. This would only happen in the case that there is no motion-based wake-up mode enabled.
Thanks to @apilat for the implementation.
Fixes #1843.
Supersedes #1207.

Fix motion service not updating when sleeping

---

src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h

If weather is available, display the cloud icon and temperature.

WatchFaceDigital: Add weather display

---

src/components/ble/SimpleWeatherService.cpp
src/components/ble/SimpleWeatherService.h

Any screen that relies on DirtyValue to display up-to-date forecast data would require the struct to provide an operator override for comparison.

SimpleWeatherService: Add forecast operator overrides

---

src/displayapp/screens/WatchFaceDigital.cpp

The weather widget is too high and could overlap the status icons. Moving it to match the rest of the face avoids this issue and makes it align with the rest of the theme.

WatchFaceDigital: Move weather widget away from status icons

---

src/displayapp/fonts/README.md

This small change makes the example consistent regarding hex and UTF-8 code, which should make it easier to follow for a newbie like myself ;-)

README: Make hex and UTF-8 code consistent for the chosen example

---

src/systemtask/SystemTask.cpp

Only thing notable here is that pushing two messages at once increases the chance of the systemTask queue getting full (which deadlocks the task as it waits forever on queue push). But I don't think it ever should fill up (10 entries), so I think it's OK.
Closes #1411

Fix chimes

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayAppRecovery.cpp
src/heartratetask/HeartRateTask.cpp
src/systemtask/SystemTask.cpp

The macro checks the variable, so we don't need to check it ourselves

Simplify ISR task wake checks

---

src/components/motion/MotionController.cpp
src/components/motion/MotionController.h

Inspired by @darkdragon-001 https://github.com/InfiniTimeOrg/InfiniTime/pull/827#issuecomment-1881580414.
Checks if the user's wrist is pointing towards the floor, rather than only the amount of roll. It will turn off the display if the watch is angled at 60 degrees or more, and rotated at least 30 degrees within the last ~600ms.

lowersleep: Improve algorithm by checking wrist angle

---

src/displayapp/DisplayApp.cpp

This prevents the application list from loading in the last used screen and instead goes back to the first screen whenever the watch face is loaded.
Fixes #2006

ApplicationList: Reset app menu screen when loading watch face

---

src/components/ble/HeartRateService.h

This issue was observed when attempting to compile the file `HeartRateController.cpp` as an individual object file with x86 gcc by using `compile_commands.json` generated by running `bear` on the project's build command.
Here is the error log - 
```bash
/usr/include/c++/11/bits/stl_algobase.h:230:9: error: expected unqualified-id before ‘const’
230 |     min(const _Tp& __a, const _Tp& __b)
|         ^~~~~
/usr/include/c++/11/bits/stl_algobase.h:230:9: error: expected ‘)’ before ‘const’
230 |     min(const _Tp& __a, const _Tp& __b)
|        ~^~~~~
|         )
/usr/include/c++/11/bits/stl_algobase.h:254:9: error: expected unqualified-id before ‘const’
254 |     max(const _Tp& __a, const _Tp& __b)
|         ^~~~~
/usr/include/c++/11/bits/stl_algobase.h:254:9: error: expected ‘)’ before …
```

Fix conflicts of min and max from stl_algo.h included from stdatomic

---

doc/code/Apps.md

- Fixed missing colon typo in template for minimal app example 
- Updated reference to Apps enum after file move

Fix and update documentation

---

src/displayapp/screens/WatchFaceAnalog.cpp
src/displayapp/screens/WatchFaceAnalog.h
src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
src/displayapp/screens/WatchFaceCasioStyleG7710.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h
src/displayapp/screens/WatchFaceInfineat.cpp
src/displayapp/screens/WatchFaceInfineat.h
src/displayapp/screens/WatchFaceTerminal.cpp
src/displayapp/screens/WatchFaceTerminal.h

There are a couple more TODOs related to using `std::chrono::year`, which was added in C++20, but not supported by GCC 10 it seems.

chrono: Resolve TODOs related to C++20 chrono feats

---

src/displayapp/screens/settings/SettingBluetooth.cpp
src/displayapp/screens/settings/SettingBluetooth.h

Emit the message BleRadioEnableToggle to DisplayApp only if the enable state of the radio has actually changed.
This fixes an issue where the BLE connected logo would disappear when opening and closing the BLE setting (without changing it) while InfiniTime was already connected to a companion app.
This fix is based on the work done by @JustScott in #1972 and also thanks to the very detailed description of the issue by @rambonette in #1961.
I think this fix makes more sense since we do not actually need to call `NimbleController::EnableRadio()` again if the radio was previously enabled and need to stay enabled. 
This change also removed the need to send the message in `SettingBluetooth::~SettingBluetooth()` by capturing this in the lambda (which is called in `CheckboxList::~CheckboxList()` …

Fix bluetooth setting : emit the radio toggle message only if the value of the setting changed

---

src/FreeRTOSConfig.h
src/displayapp/DisplayApp.cpp
src/displayapp/DisplayAppRecovery.cpp
src/displayapp/LittleVgl.cpp
src/drivers/Spi.cpp
src/drivers/Spi.h
src/drivers/SpiMaster.cpp
src/drivers/SpiMaster.h
src/drivers/SpiNorFlash.cpp
src/drivers/St7789.cpp
src/drivers/St7789.h
src/main.cpp
src/recoveryLoader.cpp

This replaces the original technique for protecting the LCD data command pin (task notifications), which didn't work super well.
This is replaced with SPI transaction hooks, where when an SPI write request (transaction) is started, you can specify a hook that runs before the write and after it finishes. It's not a super elegant solution as the hook function has to be static (if someone with C++ knowledge wants to go nuts on that be my guest!) but it's pretty straightforward and simple at least. So for the LCD, the hook just sets the data command pin to the correct setting before the transaction starts, and does nothing on transaction end. It also allows us to remove task notifications completely which saves a bit of memory on each task.
I didn't bother hooking this up for reading as …

SPI transaction hooks

---

src/drivers/St7789.cpp
src/drivers/St7789.h

- No longer spins the CPU when the display task is waiting
- Unnecessary waits removed
- Sleep in - sleep out minimum interval now respected
This all assumes the datasheet is correct :P It could definitely be inconsistent in places
I'd appreciate if it at least one reviewer could check that they interpret the datasheet the same way
https://wiki.pine64.org/images/5/54/ST7789V_v1.6.pdf
See pages 48, 49, 163, 182, 184
Split from #1869

LCD delay improvements

---

src/drivers/SpiMaster.cpp
src/drivers/SpiMaster.h

- No longer clobbers PPI and GPIOTE 0
- GPIOTE channel is allocated, PPI is a well defined constant (still CH 0)
- Refactored to use NRF SDK where appropriate
- Tracks whether workaround is active (needed for GPIOTE management)
Split from #1869

Fix erratum 58 workaround

---

src/displayapp/DisplayApp.cpp

The call to `LoadNewScreen` [here](https://github.com/InfiniTimeOrg/InfiniTime/blob/0dcfb2edb7ac071aa0a22c01609122d577d4c05d/src/displayapp/DisplayApp.cpp#L130) (and the one below it) calls `MotorController::StopRinging()` [here](https://github.com/InfiniTimeOrg/InfiniTime/blob/0dcfb2edb7ac071aa0a22c01609122d577d4c05d/src/displayapp/DisplayApp.cpp#L416), which in turn calls `xTimerStop` to stop the ringing timer. However, this timer only gets created when [`DisplayApp::InitHw`](https://github.com/InfiniTimeOrg/InfiniTime/blob/0dcfb2edb7ac071aa0a22c01609122d577d4c05d/src/displayapp/DisplayApp.cpp#L150) is called, which currently happens in [`DisplayApp::Process`](https://github.com/InfiniTimeOrg/InfiniTime/blob/0dcfb2edb7ac071aa0a22c01609122d577d4c05d/src/displayapp/DisplayApp.cpp#L143) …

Fix MotorController::Init call order

---

src/drivers/Bma421.cpp

The `Bma421::Process` function is fetching the sensor's temperature and activity output and assigning them to local variables which are never used, so this code seems to be useless and could reduce power usage.

Remove unnecessary BMA421 reads

---

src/components/ble/SimpleWeatherService.cpp
src/components/ble/SimpleWeatherService.h
src/components/datetime/DateTimeController.cpp
src/components/datetime/DateTimeController.h
src/components/datetime/TODO.md
src/displayapp/screens/WatchFaceAnalog.h
src/systemtask/SystemTask.cpp

This changes CurrentDateTime() so every call it fetches the time fresh from the RTC. Mutual exclusion must now be used to protect access to the timekeeping data as many tasks may modify it.
This change has no power / performance impact (verified by testing in #1869)
One rationale of this is simply correctness - this removes the 0.1s jitter on the current time created by the system task. This jitter was causing problems for frame pacing with always on display. But it's also nice to have correctness when it costs no performance. This also paves the way to lengthening the system task period if we wanted to explore that further. For now, that still breaks motion wake (and probably more) so it's a no go.
There's also a few other misc fixes like correcting the tick overflow calculation and …

Continuous time updates

---

README.md

As the Wiki was replaced by a new documentation website and is read-only, we should update the links, to point to the most up-to-date documentation.

README: Change links from Pine wiki to new documentation

---

src/drivers/St7789.cpp
src/drivers/St7789.h

- Address window and scrolling arguments are now sent in a single multi-byte transaction rather than multiple single-byte transactions
- Faster: much less overhead due to the workaround required to send single bytes
- Display update speed is mostly limited by the SPI bus so using the bus more efficiently helps significantly
- Improved a few other documentation bits inside the display driver
This wasn't really possible without the fixing the SPI race conditions, but with #2046 merged we can enjoy this speed up now

Batch display command arguments

---

src/components/brightness/BrightnessController.cpp
src/components/brightness/BrightnessController.h
src/components/settings/Settings.h
src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h
src/displayapp/Messages.h
src/displayapp/screens/FlashLight.cpp
src/displayapp/screens/FlashLight.h
src/displayapp/screens/settings/SettingDisplay.cpp
src/displayapp/screens/settings/SettingDisplay.h
src/drivers/St7789.cpp
src/drivers/St7789.h
src/systemtask/SystemTask.cpp

I have added an option in the "Display timeout" for an always on display. Not sure how useful this is, or how good the battery life is (will be testing this and will post a comment with how long the battery lasted).
Any suggestions on how I could possibly increase the battery with the display always on would be great.

Always on display

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h
src/displayapp/DisplayAppRecovery.cpp
src/displayapp/DisplayAppRecovery.h
src/displayapp/screens/SystemInfo.cpp
src/displayapp/screens/SystemInfo.h
src/drivers/SpiNorFlash.cpp
src/drivers/SpiNorFlash.h
src/main.cpp

This is needed since a new memory chip will be used in future batches of PineTimes.
Fixes #2096

Display the SPI flash JEDEC IDs in SystemInformation.

---

.github/workflows/main.yml

By uploading the standalone ELF build as an artifact we'll be able to use the web build of InfiniEmu to test any PRs without downloading any files.

Upload standalone ELF build as artifact

---

src/components/ble/DfuService.h
src/components/ble/HeartRateService.h
src/components/ble/NimbleController.cpp
src/components/ble/NimbleController.h

Builds on top of #897
The original problem was that an extra 128bit uuid was too big for the advertising packet
Works with OpenTracks (shows with the advertising filter on), NRF Connect shows both the DFU and HR service
Closes #895

Advertise HR service

---

src/CMakeLists.txt

Currently the NRF SDK is built with -O3 rather than -Os like with everything else
This saves a bit of flash space and performance seems unchanged to me. Thoughts on this change? I could definitely see the performance improvement being justified if it exists, but I don't have a profiler or anything.

Size optimise NRF SDK build

---

src/displayapp/screens/Timer.cpp
src/displayapp/screens/Timer.h

Currently the timer re-renders the digits every Refresh() cycle. As the digits are large on the display, this causes 100% CPU usage from DisplayApp.
This PR changes the timer to use DirtyValue so it only re-renders the digits when they change.

Use DirtyValue for timer

---

src/displayapp/DisplayApp.cpp
src/displayapp/Messages.h
src/systemtask/SystemTask.cpp

There are some old left over messages from before `RestoreBrightness` became `NotifyDeviceActivity`, and also some other ones that are well before my time. Since screens pull the time directly from the time controller, removing `UpdateDateTime` seems justified. And I can't think of anything that'd want to send `DimScreen` to DisplayApp, so I removed this too (the message is currently unused)

Clean unused DisplayApp messages

---

src/systemtask/SystemMonitor.cpp

The debugging monitor serves no purpose if a logger isn't available, so the preprocessor check now verifies exactly that. Since the about screen relies on `configUSE_TRACE_FACILITY` (and presumably won't compile without), I thought there is no point checking that too

Restrict debugging monitor to debug builds

---

src/displayapp/screens/Notifications.cpp

I found it slightly annoying that dismissing all notifications leaves me with a "No notification to display" message. Instead of dismissing to a relatively useless message, dismiss to watchface.

notifications: Dismiss to watchface when empty

---

src/components/ble/DfuService.cpp
src/components/ble/NimbleController.cpp
src/displayapp/DisplayApp.cpp
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

Currently SystemTask is somewhat fragile to duplicate state transitions and unusual state transition message orders. Most notably this can cause it to get stuck in `GoingToSleep` in some scenarios.
This PR introduces GoToSleep() and changes GoToRunning() as immediately executable functions. The guarantee that state transitions happen immediately reduces complexity when it comes to ensuring the device is awake for events such as Chimes 
Fixes part of #1790 #2012 (there may be other issues contributing to these, but this is probably part of it)

SystemTask state refactor

---

src/CMakeLists.txt
src/displayapp/screens/Alarm.cpp
src/displayapp/screens/Alarm.h
src/displayapp/screens/FlashLight.cpp
src/displayapp/screens/FlashLight.h
src/displayapp/screens/HeartRate.cpp
src/displayapp/screens/HeartRate.h
src/displayapp/screens/Metronome.cpp
src/displayapp/screens/Metronome.h
src/displayapp/screens/Notifications.cpp
src/displayapp/screens/Notifications.h
src/displayapp/screens/StopWatch.cpp
src/displayapp/screens/StopWatch.h
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h
src/systemtask/WakeLock.cpp
src/systemtask/WakeLock.h

Rather than tracking whether sleeping is disabled with a boolean, this moves it to a counter which records the number of requests to keep the device awake. When this counter is zero, sleeping is possible. This prevents one task from enabling sleeping when another task still wants sleeping disabled.

Refactor doNotGoToSleep to a wakelock counter

---

src/components/heartrate/Ppg.cpp
src/components/heartrate/Ppg.h
src/drivers/Hrs3300.cpp
src/drivers/Hrs3300.h
src/heartratetask/HeartRateTask.cpp

- Combines the reading of all HRS3300 registers into one I2C read so data is not partial
- Downsizes both HRS and ALS to 16bit as the sensor does not generate larger than 16bit values in its current configuration
- Increasing the resolution by 1 bit doubles the sensor acquisition time, since we are already at 10Hz we are never going to use a higher resolution
- The PPG algorithm buffers for ALS/HRS are already 16bit anyway
- Removes functions for setting gain / drive that are unused throughout the codebase

Atomic HRS reads

---

src/drivers/Hrs3300.cpp

Fix for Hrs3300 PR about Atomic HRS reads:
https://github.com/InfiniTimeOrg/InfiniTime/pull/1845
We use `std::begin` and `std::end`, but we don't include one of the headers that define those functions.
See https://en.cppreference.com/w/cpp/iterator/begin for a list of headers that define `std::begin` and `std::end`.
Starting with GCC 14 this leads to a compilation error presumably because they cleaned up their headers.
Fix code by inlcuding `<iterator>`

Hrs3300: fix includes for std::begin/std::end

---

src/components/alarm/AlarmController.cpp
src/components/alarm/AlarmController.h
src/displayapp/screens/Alarm.cpp
src/main.cpp
src/systemtask/SystemTask.cpp

rebase of https://github.com/InfiniTimeOrg/InfiniTime/pull/1333 with additional `SaveAlarm()` function as described below
---
Save the set alarm time to the SPI NOR flash, so it does not reset to
the default value when the watch resets, e.g. due to watchdog timeout
or a firmware update
Introduce `SaveAlarm()` member function which saves to file only if the
alarm setting is changed.
The `alarmChanged` boolean flag mimics the behavior of `settingsChanged`
flag from `Settings.h`
Also mark the ~~`SaveAlarmToFile()`~~ ~~`Save()`~~ `SaveSettingsToFile` function const, as it doesn't change
anything in the `AlarmController` object.
---
This PR needs https://github.com/InfiniTimeOrg/InfiniSim/pull/67 to work on `InfiniSim`
--- 
Fixes: https://github.com/InfiniTimeOrg/InfiniTime/issues/1330

Alarm persist to flash

---

src/components/ble/MusicService.cpp
src/components/ble/MusicService.h

Add includes for the directly used data type `TickType_t` in the header and the function `xTaskGetTickCount` from FreeRTOS's `task.h`
I found out while slimming down InfiniSim and trying to use `MusicService.h` from InfiniTime directly

MusicService: add missing includes for TickType_t and xTaskGetTickCount

---

.gitmodules

The submodule isn't used anymore. Remove the submodule reference completely.

Remove unused submodule QCBOR

---

src/components/datetime/DateTimeController.cpp

datetime: Set the default year to the year during compile

---

src/components/ble/SimpleWeatherService.h

not <vector> as that is what is actually used.
Fixes build failure
InfiniTime/src/components/ble/SimpleWeatherService.h:86:18: error: field ‘location’ has incomplete type ‘Pinetime::Controllers::SimpleWeatherService::Location’ {aka ‘std::array<char, 33>’
with g++ on Debian 12.2.0-14 and libstdc++-12-dev 12.2.0-14

SimpleWeatherService #include <array>

---

src/displayapp/DisplayApp.cpp
src/displayapp/LittleVgl.cpp
src/displayapp/LittleVgl.h
src/main.cpp
src/systemtask/Messages.h
src/systemtask/SystemTask.cpp
src/systemtask/SystemTask.h

Currently if the touch panel is pressed when DisplayApp goes to sleep, the finger up event gets dropped. This causes LVGL to think the finger is never released from the touch panel, so it prevents the device from sleeping. This PR clears the tapped state when going to sleep so the internal LVGL state remains consistent with the real touch panel state.
Fixes part of #1790 #2012 (there may be other issues contributing to these, but this is probably part of it)

Clear ongoing taps when going to sleep

---

src/displayapp/screens/settings/Settings.h

Proposal to update Date&Time label for issue #1746

Update Date&Time settings label for "Date & Time"

---

README.md

The openrepos contain obsolete version (description on the openrepos page says that). New SailfishOS version is in chum repo. Additionally, there is Ubuntu Touch and Flatpak version.

Update Amazfish details in README.md

---

.github/workflows/main.yml

ci: Normalise slash-containing `github.head_ref` values

---

docker/Dockerfile

Fix error when compiling the Pinetime using the Docker image. If done with Docker, the container does not trust the /sources folder, leading to a blank response of the command that grabs the git commit `git rev-parse --short HEAD`.
```
fatal: detected dubious ownership in repository at '/sources'
To add an exception for this directory, call:
git config --global --add safe.directory /sources
PROJECT_GIT_COMMIT_HASH_SUCCESS? 128
BUILD CONFIGURATION
-------------------
* Mode : Release
* Version : 1.3.0
* Toolchain : /opt/gcc-arm-none-eabi-10.3-2021.10
* GitRef(S) :
* NRF52 SDK : /opt/nRF5_SDK_15.3.0_59ac345
* Target device : PINETIME
* Build DFU (using adafruit-nrfutil) : Enabled
* Build resources : Enabled
```
If the `git config --global --add safe.directory /sources` is added to the …

Fix git hash calculation with Docker build

---

src/displayapp/fonts/CMakeLists.txt
src/resources/CMakeLists.txt

If I use python3.13 as my system python version, but I use python3.12 to create venv, cmake will find /usr/bin/python3.13 but not venv
Because cmake will use the latest version.
From https://cmake.org/cmake/help/latest/module/FindPython3.html
> Note
> This hint has the lowest priority of all hints, so even if, for example, you specify IronPython first and CPython in second, a python product based on CPython can be selected because, for example with Python3_FIND_STRATEGY=LOCATION, each location will be search first for IronPython and second for CPython. 
Refer: https://discourse.cmake.org/t/find-package-python3-is-not-finding-the-correct-python/10563

cmake: fix python path with use multi-version python

---

src/displayapp/screens/Weather.cpp

When converting to imperial units, the min and max temperatures were incorrectly inverted, causing confusion in the display.
Fixes https://github.com/InfiniTimeOrg/InfiniTime/issues/2183

weather: Fix inverted imperial forecast temperatures

---

src/displayapp/DisplayApp.cpp
src/displayapp/screens/ApplicationList.cpp
src/displayapp/screens/ApplicationList.h
src/displayapp/screens/Tile.cpp
src/displayapp/screens/Tile.h
src/displayapp/screens/WatchFaceDigital.cpp
src/displayapp/screens/WatchFaceDigital.h
src/displayapp/screens/settings/QuickSettings.cpp
src/displayapp/screens/settings/QuickSettings.h
src/displayapp/widgets/StatusIcons.cpp
src/displayapp/widgets/StatusIcons.h

I would like to know if the alarm is active on Watch Face Digital screen. 
I made an prototype with InfiniSim and it looks that it works as expected:
However, I have only sealed version of PineTime and this is my first attempt to make something for embedded device. I will be happy if someone can check if this actually works on real device. I am looking forward for your feedback.

Show alarm controller state in status icons

---

src/components/alarm/AlarmController.cpp
src/displayapp/screens/Alarm.cpp

Fixes #2206
When Alerting, the handlers for swiping and hard- and software buttons correctly deal with this.
The handler for time value changes did not.
~~Now a value change will also stop the alert.
For the scenario presented in #2206 (makeshift snooze), this means that after setting a new time, the new alarm also needs to be enabled again. However, I think this is not a problem, because the UI clearly presents that the alarm is disabled and it can be re-enabled exactly like setting an alarm always works.~~
Edit: Now fixing the problem by making the value change impossible in the first place by simplifying the alerting screen.

Alarm: Simplify alarm alerting screen (and fix bug with alerting on time value change)

---

.github/workflows/format.yml
.github/workflows/main.yml

It seems v3 can be directly replaced by v4.
I have seen just issue with naming infinitisim artifact, which is unrelated with migration to v4. See https://github.com/InfiniTimeOrg/InfiniTime/issues/2223

CI: Use artifact v4 instead of v3

---

.github/workflows/main.yml

Using nightly.link and corsproxy.io we can generate a link that, when clicked, will direct users to a build of the latest commit of a pull request running on InfiniEmu.
It's also worth noting that GitHub actions artifacts expire after 90 days.

Add "Run on InfiniEmu" link to pull requests, update actions/upload-artifact

---

src/displayapp/screens/Notifications.cpp

This PR is a small change and it might very well be up to preference.
In the little notifications screen above the watchface, the "Notification" as well as "No notifications to display" is now changed to "Notification**s**" and "No notification**s** to display".
In my opinion using the plural makes more sense here, since the screen can show more than just one notification.
Feel free to tell me what you think!
Here's a pic of how it looks like in InfiniEmu:

Notification -> Notifications

---

.gitattributes

Proper fix for #1275 that does no longer require manual intervention. 
On Windows, git has `core.autocrlf=true` set at _system_ level, hence any Windows user who has not changed their _global_ git config will checkout all text files with CRLF line endings. For some files this seems to cause build issues.
With this change, I can build using docker on Windows 11 as follows:
```pwsh
git clone https://github.com/madmini/InfiniTime.git --branch fix/eol-on-windows
cd InfiniTime
git submodule update --init
docker run --rm -it -v ${PWD}:/sources infinitime/infinitime-build
```
Without the change, the build fails with an error that matches the one described in #1275:
```
...
[ 34%] Linking C static library libnimble.a
[ 34%] Built target nimble
gmake: *** [Makefile:91: all] Error 2
```
<hr /> …

Fix EOL related build issues on Windows

---

src/displayapp/screens/WatchFaceInfineat.cpp
src/displayapp/screens/WatchFaceInfineat.h

This PR prevents the blocking issue identified in #2245 
This is a better solution than the one proposed in #2248

Prevents blocking when Infineat watchface is charging

---

doc/code/Apps.md

The Apps.h header file is located a directory lower than the path that is used here.

Documentation: Minor fix to example app code

---

src/displayapp/screens/SystemInfo.cpp

There was a newline at the end of the last line on the third screen, which was causing the label to not be centered vertically. Removing it fixes the centering.
Here are some before and after screenshots for clarity.
Thank You!

Fix about screen vertical centering.

---

.github/workflows/main.yml

Fixes the `PROJECT_GIT_COMMIT_HASH` not getting set in Github builds.
Previously, the step that should get the short ref using git failed:
```
fatal: detected dubious ownership in repository at '/__w/InfiniTime/InfiniTime'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/InfiniTime/InfiniTime
```
The checkout action is supposed to do that already, but for some reason it's not working:
```
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /__w/InfiniTime/InfiniTime
```
It looks like this is an issue more people are facing, but for some reason the issue is closed: https://github.com/actions/checkout/issues/1048
The proposed fix of setting the user wasn't working, so …

Fixes the short ref not being set in Github builds

---

src/components/ble/NotificationManager.h

Prevents reading uninitialised memory if notification gets cut off due to being more than 100 chars. The last character is assumed to be `\0`, but it is actually uninitialised.

notification: Initialise message

---

doc/buildAndProgram.md
docker/build.sh

It appears that NRF has moved the download to a new location. The old URL is now a 404. 
Update the build script and README to use the same URL the download website currently provides.
Fixes #2267

Fix nrf sdk download links

---

docker/build.sh

The upstream NRF-SDK download url and zip archive filename changed, which was fixed with https://github.com/InfiniTimeOrg/InfiniTime/pull/2270
But the archive contents stayed the same, with the "old" folder name.
After #2270 we have basically the same docker-container as before the PR, but the `GetNrfSdk` function of the `build.sh` script is called again during firmware build time as the expected foldername for the SDK isn't the same as the zip filename:
```sh
[ ! -d "$TOOLS_DIR/$NRF_SDK_VER" ] && GetNrfSdk
```
Then during the build the `buils.sh` script tries to execute `GetNrfSdk` again, which fails as the files already exist resulting in the following error:
```
replace /opt/nRF5_SDK_15.3.0_59ac345/components/802_15_4/api/HAL/hal_atomic.h? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL …
```

docker: fix NRF_SDK download and subsequent build.sh

---

src/displayapp/screens/settings/SettingWakeUp.cpp

and save a few bytes of heap memory

set static text as static text

---

src/FreeRTOSConfig.h

We don't use any of them, so may as well turn them off

Disable legacy FreeRTOS functions

---

src/displayapp/DisplayApp.cpp
src/displayapp/DisplayApp.h

Loading the watchface in the SystemTask context creates a lot of stack pressure as the SystemTask stack is much smaller
This might also fix other bad behaviour that occurs with watchfaces on first load e.g as reported by feksa in the pinetime-dev channel. Not sure though, haven't looked at the exact cause

Initialise DisplayApp components in DisplayApp context

---

src/displayapp/DisplayApp.cpp
src/displayapp/UserApps.h
src/displayapp/screens/Alarm.h
src/displayapp/screens/Calculator.h
src/displayapp/screens/Dice.h
src/displayapp/screens/HeartRate.h
src/displayapp/screens/InfiniPaint.h
src/displayapp/screens/Metronome.h
src/displayapp/screens/Motion.h
src/displayapp/screens/Music.h
src/displayapp/screens/Navigation.h
src/displayapp/screens/Paddle.h
src/displayapp/screens/Steps.h
src/displayapp/screens/StopWatch.h
src/displayapp/screens/Timer.h
src/displayapp/screens/Twos.h
src/displayapp/screens/Weather.h

Commit 0aead42fdf51 ("navigation: Add is available (#1847)") added the ability to draw the app icon in grey and in a disabled state when some prerequisits were not met. Only the Navigation app was using this mechanism due to its icons being stored in the external memory and possibly missing.
Commit 63e0c4f4efb0 ("Application selection at build time") broke this by always setting the state as true:
for (const auto& userApp : userApps) {
apps[i++] = Screens::Tile::Applications {userApp.icon, userApp.app, true};
}
Fix this by creating an isAvailable() strcuture in the app classes, similar
to how the Watchfaces handle the same problem of checking availability.

navigation: fix greying out the app icon if not enabled

---

src/drivers/Cst816s.cpp

Split from #2325
> According to the datasheet there is nothing at register 0. So I figured we probably shouldn't be trying to read it. It's a machine translation though so maybe something is missing? https://wiki.pine64.org/images/2/2f/CST816S.zip

Remove redundant touchpanel read
